<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="NvtFwCombiner.Domain.Tests" />
    <InternalsVisibleTo Include="NvtFwCombiner.Application.Tests" />
    <InternalsVisibleTo Include="NvtFwCombiner.Bootstrap.Tests" />
    <InternalsVisibleTo Include="NvtFwCombiner.ProfileContract.Tests" />
    <InternalsVisibleTo Include="NvtFwCombiner.Profiles" />
  </ItemGroup>

</Project>
