// Resource bags intentionally expose many concise bindable labels; XML comments on each label add noise.
#pragma warning disable CS1591

namespace NvtFwCombiner.Presentation.Avalonia.ViewModels;

public sealed partial class ShellTextResources
{
    private static ShellTextResources CreateLocalized(ShellLanguage language)
    {
        T Pick<T>(T english, T traditionalChinese)
        {
            return language == ShellLanguage.ChineseTraditional ? traditionalChinese : english;
        }

        return new ShellTextResources
        {
            Language = language,
            HomeLabel = Pick("Home", "首頁"),
            WorkspaceTitle = Pick("Merge / Replace workspace", "合併 / 取代工作區"),
            WorkspaceSummary = Pick("Production-backed shell with built-in profiles, flash-map catalog, and report review.", "使用內建 profile、flash-map catalog 與 report review 的生產導向介面。"),
            PreviewActionLabel = Pick("Preview", "預覽"),
            BuildActionLabel = Pick("Build", "建立"),
            PreviewRunProgressAccessibleLabel = Pick("Preview in progress", "正在預覽"),
            BuildRunProgressAccessibleLabel = Pick("Build in progress", "正在建立"),
            ReportModalActionLabel = "Report",
            DeviceContextTitle = Pick("Device context", "裝置條件"),
            IcLabel = "IC",
            NumberLabel = Pick("Number", "數量"),
            DeviceContextStatus = Pick("refresh profile, slots, validation", "刷新 profile、slot、validation"),
            SettingsPreview = Pick(
                new PlanningCardText(
                    "Settings",
                    "Review installed capabilities and working preferences.",
                    [
                        "Version and supported IC count",
                        "Executable profile and tool coverage",
                        "Theme and language preference",
                    ],
                    "Implemented settings only"),
                new PlanningCardText(
                    "設定",
                    "查看已安裝功能與實際生效的偏好設定。",
                    [
                        "版本與支援 IC 數量",
                        "可執行 profile 與 tool coverage",
                        "主題與語言偏好",
                    ],
                    "只保留已實作設定")),
            MergePreview = Pick(
                new PlanningCardText(
                    "Merge",
                    "Standard Merge workflow.",
                    [
                        "Profile: built-in Standard Merge",
                        "Slots: DP, TP, optional LD",
                        "950/951 DP Perspective policy",
                    ],
                    "Build wired"),
                new PlanningCardText(
                    "合併",
                    "Standard Merge 流程。",
                    [
                        "Profile：內建 Standard Merge",
                        "Slots：DP、TP、選用 LD",
                        "950/951 DP Perspective policy",
                    ],
                    "Build 已串接")),
            ReplacePreview = Pick(
                new PlanningCardText(
                    "Replace",
                    "DP, CtrlRAM, and General policies.",
                    [
                        "Device context: shared IC and Number",
                        "DP Replace includes separate DP and LD payloads",
                        "CtrlRAM Replace uses approved CtrlRAM regions",
                        "CRC/header: combiner.exe postbuild core",
                    ],
                    "Build wired; CtrlRAM postbuild enabled"),
                new PlanningCardText(
                    "取代",
                    "DP、CtrlRAM 與 General policy。",
                    [
                        "裝置條件：共用 IC 與數量",
                        "DP Replace 包含分開的 DP 與 LD payload",
                        "CtrlRAM Replace 使用核准的 CtrlRAM regions",
                        "CRC/header：combiner.exe postbuild core",
                    ],
                    "Build 已串接；CtrlRAM postbuild 已啟用")),
            InitialRunTitle = Pick("No run yet", "尚未執行"),
            InitialRunDetail = Pick("Drop required BIN files, then run Build.", "放入必要 BIN 檔後即可建立。"),
            NoOutputLabel = Pick("No output", "無輸出"),
            WorkflowKicker = Pick("WORKFLOW", "流程"),
            OpenLabel = Pick("Open", "開啟"),
            PendingLabel = Pick("Pending", "待實作"),
            LoadJsonLabel = Pick("Load JSON", "載入 JSON"),
            LoadJsonTooltip = Pick("Load report JSON", "載入 report JSON"),
            BackTooltip = Pick("Back", "返回"),
            ModeLabel = Pick("Mode", "模式"),
            TargetsLabel = Pick("Targets", "目標"),
            ReviewReplacementInputsTooltip = Pick("Review selected replacement inputs", "查看已選擇的 replacement inputs"),
            InputFilesTitle = Pick("Input files", "輸入檔案"),
            OutputLayoutTitle = Pick("Output layout", "輸出配置"),
            PlanTitle = Pick("Plan", "計畫"),
            ValidationTitle = Pick("Validation", "驗證"),
            GeneralReplaceMappingTitle = "General replace mapping",
            GeneralMergeMappingTitle = "General merge mapping",
            ExplicitMappingsTitle = Pick("Explicit mappings", "明確 mappings"),
            AddRangeLabel = Pick("+ Add range", "+ 新增範圍"),
            AddMappingLabel = Pick("+ Add mapping", "+ 新增 mapping"),
            StartLabel = Pick("Start", "起始"),
            EndLabel = Pick("End", "結束"),
            SourceStartLabel = Pick("Source start", "來源起始"),
            TargetStartLabel = Pick("Target start", "目標起始"),
            LengthLabel = Pick("Length", "長度"),
            SourceBinLabel = "Source BIN",
            ReplacementBinLabel = "Replacement BIN",
            OutputLengthLabel = Pick("Output length", "輸出長度"),
            OutputLengthPlaceholder = "0x...",
            BrowseLabel = Pick("Browse", "瀏覽"),
            RequiredLabel = Pick("Required", "必填"),
            OptionalLabel = Pick("Optional", "選填"),
            NoBinSelectedLabel = Pick("No BIN selected", "尚未選擇 BIN"),
            MergeDpSlotDescription = Pick("Display payload for Standard Merge", "Standard Merge 的 Display payload"),
            MergeTpSlotDescription = Pick("Touch payload for Standard Merge", "Standard Merge 的 Touch payload"),
            MergeLdSlotDescription = Pick("Required only when the selected profile uses LD", "只有選定 profile 使用 LD 時才需要"),
            DpReplacementBinTitle = "DP replacement source",
            SelectReplacementBinTooltip = Pick("Select replacement BIN", "選擇 replacement BIN"),
            SelectSourceBinTooltip = Pick("Select source BIN", "選擇 source BIN"),
            RemoveRangeTooltip = Pick("Remove range", "移除範圍"),
            RemoveMappingTooltip = Pick("Remove mapping", "移除 mapping"),
            GeneralReplaceRuleBaseTitle = "Base image",
            GeneralReplaceRuleBaseDetail = Pick("Unmapped bytes stay from the selected base BIN.", "未 mapping 的 bytes 會保留選定 base BIN 的內容。"),
            GeneralReplaceRuleBoundsTitle = Pick("Target bounds", "目標邊界"),
            GeneralReplaceRuleBoundsDetail = Pick("Ranges must fit the base image and avoid protected regions.", "範圍必須落在 base image 內並避開 protected regions。"),
            GeneralReplaceRuleLengthTitle = Pick("Input length", "輸入長度"),
            GeneralReplaceRuleLengthDetail = Pick("Replacement BIN data must cover the mapped range length.", "Replacement BIN data 必須覆蓋 mapping 範圍長度。"),
            GeneralReplaceValidationDetail = Pick("Validated execution uses compiled explicit mappings; TP ranges require approved Combiner CRC/header refresh.", "執行時會使用已編譯的 explicit mappings；TP 範圍需要核准的 Combiner CRC/header refresh。"),
            GeneralReplaceMappingsDetail = Pick("Each row maps one inclusive target range to one replacement BIN.", "每列將一個 inclusive target range 對應到一個 replacement BIN。"),
            HexEditorSaveAsLabel = Pick("Save as...", "另存新檔..."),
            HexEditorSaveConfirmationTitle = Pick("Save new BIN?", "儲存新的 BIN？"),
            HexEditorSaveConfirmationDetail = Pick("Edits remain in memory until export. Save As writes a new BIN only; it never changes the opened source BIN and does not run firmware validation or postbuild.", "修改只保留在記憶體直到輸出。另存新檔只會寫出新的 BIN，絕不改寫已開啟來源，且不會執行韌體驗證或 postbuild。"),
            HexEditorSaveConfirmationActionLabel = Pick("Choose output", "選擇輸出位置"),
            GeneralMergeMappingDetail = Pick("Copy explicit source BIN ranges into a blank output image. No postbuild command runs.", "將明確 source BIN ranges 複製到 blank output image；不執行 postbuild command。"),
            GeneralMergeMappingsDetail = Pick("Each row copies one source BIN range to one output target range.", "每列將一個 source BIN range 複製到一個 output target range。"),
            CtrlRamInputFilesDetail = Pick("When the selected IC/profile supports it, use TP FW or a complete Flash Code as the base firmware BIN. Drop files only for CtrlRAM areas you want to change; empty areas stay from the base firmware.", "僅在選定的 IC/profile 支援時，Base firmware BIN 才可使用 TP FW 或完整 Flash Code。只放入要更動的 CtrlRAM 區域檔案；未放入的區域保留 base firmware。"),
            CtrlRamFirmwareVersionTitle = Pick("TP version for this output", "設定這次輸出的 TP 版本"),
            CtrlRamFirmwareVersionDetail = Pick("Choose how the output version is prepared before the approved CtrlRAM postbuild runs.", "選擇核准的 CtrlRAM postbuild 執行前，要如何準備輸出版本。"),
            CtrlRamFirmwareVersionKeepLabel = Pick("✓  Keep base version", "✓  沿用 Base 版本"),
            CtrlRamFirmwareVersionEditLabel = Pick("✎  Set a new version", "✎  設定新版本"),
            CtrlRamFirmwareVersionCurrentLabel = Pick("Base firmware TP version", "Base firmware 的 TP 版本"),
            CtrlRamFirmwareVersionByteLabel = Pick("FW version", "FW 版本"),
            CtrlRamFirmwareSubVersionByteLabel = Pick("FW sub-version", "FW 子版本"),
            CtrlRamFirmwareVersionSourceDetail = Pick("Read from the verified NVT Backup in the base firmware. Postbuild propagates the chosen value to the output Backup.", "此值取自 base firmware 內已驗證的 NVT Backup；postbuild 會把選定版本帶到輸出 Backup。"),
            CtrlRamFirmwareVersionEditUnavailableDetail = Pick("The NVT Backup version metadata is unavailable or invalid, so only keeping the original version is allowed.", "NVT Backup 的版本資訊不存在或驗證失敗，因此只能維持原本版本。"),
            CtrlRamFirmwareVersionInvalidByteDetail = Pick("Enter each version field as one hexadecimal byte from 00 to FF.", "每個版本欄位須輸入 00 到 FF 的一個十六進位 byte。"),
            CtrlRamFirmwareVersionChooseOutputLabel = Pick("Continue to output", "繼續選擇輸出"),
            AbCodeMergeTitle = "AB Code Merge",
            AbCodeMergeDetail = Pick("Reserved until the dedicated AB Code profile and TP CRC/start-address behavior are approved.", "保留到 dedicated AB Code profile 與 TP CRC/start-address 行為核准後再啟用。"),
            SettingsOverviewTitle = Pick("Product information", "產品資訊"),
            SettingsOverviewSubtitle = Pick("Installed version and executable profile coverage.", "已安裝版本與可執行 profile coverage。"),
            SettingsCapabilitiesTitle = Pick("Implemented capabilities", "已實作功能"),
            SettingsCapabilitiesSubtitle = Pick("Catalog-backed CtrlRAM and external processor coverage.", "由 catalog 提供的 CtrlRAM 與外部 processor coverage。"),
            SettingsPreferencesTitle = Pick("Preferences", "偏好設定"),
            SettingsPreferencesSubtitle = Pick("Preferences that take effect now and are restored on startup.", "立即生效並在啟動時還原的本機偏好。"),
            ThemeLabel = Pick("Theme", "主題"),
            LanguageLabel = Pick("Language", "語言"),
            ReportToastTitle = "Report",
            ReplaceSelectionTitle = "Replace selection",
            CloseSelectionTooltip = Pick("Close selection overview", "關閉 selection overview"),
            SelectedReplacementsTitle = Pick("Selected replacements", "已選 replacements"),
            RequiredBeforeBuildTitle = Pick("Required before Build", "Build 前必填"),
            CloseLabel = Pick("Close", "關閉"),
            SaveReportLabel = Pick("Save report", "儲存 report"),
            CloseReportTooltip = Pick("Close report", "關閉 report"),
            ReportHistoryTitle = "Report history",
            BackToReportLabel = Pick("Back to report", "回到 report"),
            ClearAllLabel = Pick("Clear all", "全部清除"),
            ClearHistoryLabel = Pick("Clear history", "清除 history"),
            ClearHistoryTooltip = Pick("Clear all report history (Ctrl+Shift+Delete)", "清除全部 report history (Ctrl+Shift+Delete)"),
            NoReportHistoryLabel = Pick("No report history.", "目前沒有 report history。"),
            RunLabel = Pick("Run", "執行"),
            OutputLabel = Pick("Output", "輸出"),
            RunResultReportReadyLabel = Pick("report ready", "report 已就緒"),
            ChangeReviewTitle = Pick("Change review", "差異審查"),
            EvidenceTitle = Pick("Audit details", "審查明細"),
            TraceLabel = "trace",
            OpenReportHistoryTooltip = Pick("Open report history (Ctrl+H)", "開啟 report history (Ctrl+H)"),
            OpenReportHistoryAutomationName = Pick("Open report history", "開啟 report history"),
            ReportTabInputs = Pick("Inputs", "輸入"),
            ReportTabChanges = Pick("Changes", "差異"),
            ReportTabOperations = Pick("Operations", "操作"),
            ReportTabPostbuild = "Postbuild",
            ReportTabIssues = Pick("Issues", "問題"),
            ReportTabRaw = Pick("Raw", "原始資料"),
            RawReportTitle = Pick("Raw report JSON", "原始 report JSON"),
            RawReportDetail = Pick("Audit-only source data. Use the other tabs for normal review.", "僅供稽核與除錯；一般檢視請使用其他分頁。"),
            RunMetadataTitle = Pick("Run metadata", "執行資訊"),
            ReportFileLabel = Pick("Report file", "Report 檔案"),
            FileLabel = Pick("File", "檔案"),
            SizeLabel = Pick("Size", "大小"),
            StateLabel = Pick("State", "狀態"),
            StatusLabel = Pick("Status", "狀態"),
            ArtifactPathLabel = "Artifact path",
            InputsAndHashesTitle = Pick("Input files", "輸入檔案"),
            EmptyInputsMessage = Pick("No input artifact rows were recorded in this report.", "此 report 沒有記錄 input artifact rows。"),
            EmptyByteChangesMessage = Pick("No output differences or changed ranges were recorded.", "此 report 沒有記錄 output differences 或 changed ranges。"),
            OutputChangesTitle = Pick("Output changes", "輸出差異"),
            RangeLabel = Pick("Range", "範圍"),
            ResultLabel = Pick("Result", "結果"),
            DetailLabel = Pick("Detail", "細節"),
            ChangedRangesTitle = "Changed ranges",
            EmptyOperationsMessage = Pick("No copy/process operation steps were recorded.", "此 report 沒有記錄 copy/process operation steps。"),
            OperationStepsTitle = "Operation steps",
            KindLabel = "Kind",
            SourceLabel = "Source",
            EmptyPostbuildMessage = Pick("No external postbuild/header refresh command was recorded.", "此 report 沒有記錄 external postbuild/header refresh command。"),
            HeaderRefreshTraceTitle = "Header refresh trace",
            EmptyIssuesMessage = Pick("No issues or warnings were recorded.", "此 report 沒有記錄 issues 或 warnings。"),
            NoActionRequiredTitle = Pick("No action required", "不需處理"),
            IssuesAndWarningsTitle = Pick("Issues and warnings", "問題與警告"),
            RangeTableTitle = "Range table",
            AddressSpaceLabel = "Address space",
            CopyCommandTooltip = Pick("Copy command evidence", "複製命令證據"),
            DeleteReportTooltip = Pick("Delete this report", "刪除此 report"),
            MergeModeTooltip = Pick("Select Standard, reserved AB Code, or high-freedom General Merge.", "選擇 Standard、保留的 AB Code 或高自由度 General Merge。"),
            WorkflowContextReplaceDetail = Pick("Choose the IC and IC count before opening Replace. You can change them later from the shared context row.", "進入 Replace 前先選擇 IC 與 IC 數量；之後仍可從共用條件列調整。"),
            WorkflowContextMergeDetail = Pick("Choose the IC before opening Merge. IC count is not part of the Standard or General Merge authoring context.", "進入 Merge 前先選擇 IC；Standard 與 General Merge 的 authoring context 不使用 IC 數量。"),
            WorkflowContextSafetyDetail = Pick("This only selects the catalog context. It does not inspect, modify, or write any firmware file.", "這只會選擇 catalog 條件，不會讀取、修改或寫入任何 firmware 檔案。"),
            FirmwareIcMismatchTitle = Pick("Selected BIN suggests another IC", "選擇的 BIN 顯示另一個 IC"),
            FirmwareIcMismatchDetail = Pick("A marker found in the file name or printable header text differs from the current catalog context. This is a prompt only; it does not validate the BIN or change it.", "檔名或可讀 header 文字中的 IC marker 與目前 catalog 條件不同。此提示不會驗證或修改 BIN，也不會自動變更 IC。"),
            FirmwareIcMismatchCurrentLabel = Pick("Current IC", "目前 IC"),
            FirmwareIcMismatchDetectedLabel = Pick("Detected marker", "偵測 marker"),
            FirmwareIcMismatchKeepLabel = Pick("Keep current IC", "維持目前 IC"),
            FirmwareIcMismatchUseDetectedLabel = Pick("Use detected IC", "使用偵測到的 IC"),
            ContextUpdatedToastTitle = Pick("Context updated", "條件已更新"),
            UtilToolsLabel = Pick("UTIL", "工具"),
            UtilToolsHomeTitle = Pick("Tool", "工具"),
            UtilToolsHomeDetail = Pick("Inspect and edit raw BIN files.", "檢視與編輯原始 BIN。"),
            HexEditorContextInsertZeroBeforeLabel = Pick("Insert 00 before this byte", "在此 byte 前插入 00"),
            HexEditorContextInsertZeroAfterLabel = Pick("Insert 00 after this byte", "在此 byte 後插入 00"),
            HexEditorContextInsertBytesBeforeLabel = Pick("Insert N bytes before...", "在此 byte 前插入 N bytes..."),
            HexEditorContextInsertBytesAfterLabel = Pick("Insert N bytes after...", "在此 byte 後插入 N bytes..."),
            HexEditorContextDeleteByteLabel = Pick("Delete this byte (shift later bytes left)", "刪除此 byte（後續 byte 左移）"),
            HexEditorContextSetToZeroLabel = Pick("Set this byte to 00", "將此 byte 設為 00"),
            HexEditorContextSetToFfLabel = Pick("Set this byte to FF", "將此 byte 設為 FF"),
            HexEditorContextGoToBlockStartLabel = Pick("Go to block start", "跳至區塊開頭"),
            HexEditorContextGoToBlockEndLabel = Pick("Go to block end", "跳至區塊結尾"),
            HexEditorSourceReadyDetail = Pick("In memory: 0x{0:X} bytes | {1} edit(s)", "記憶體中：0x{0:X} bytes | {1} 筆修改"),
            HexEditorSourceEmptyDetail = Pick("Open a BIN to inspect and edit a private in-memory work copy.", "開啟 BIN 後即可在私有記憶體工作副本中檢視與修改。"),
            HexEditorSaveCompletedDetail = Pick("Saved a new BIN: {0}", "已儲存新的 BIN：{0}"),
            HexEditorFileOperationFailedDetail = Pick("The BIN operation could not be completed.", "無法完成 BIN 操作。"),
            HexEditorNothingToUndoDetail = Pick("There is no in-memory change to undo.", "沒有可復原的記憶體修改。"),
            HexEditorNothingToRedoDetail = Pick("There is no reverted change to redo.", "沒有可重做的修改。"),
            HexEditorTitle = "Hex Editor",
            HexEditorDetail = Pick("Raw BIN utility. Edit an in-memory work copy, then Save As a new BIN. No IC, profile, CRC, or postbuild rule is applied.", "純 BIN 工具。修改只存在記憶體工作副本，另存新檔才輸出；不套用 IC、profile、CRC 或 postbuild 規則。"),
            HexEditorGoToAddressLabel = Pick("Go to address", "跳至位址"),
            HexEditorAsciiSearchLabel = Pick("Find ASCII", "搜尋 ASCII"),
            HexEditorAsciiSearchPlaceholder = Pick("Find ASCII", "搜尋 ASCII"),
            HexEditorAsciiSearchNotFoundDetail = Pick("ASCII text was not found in the in-memory BIN.", "目前記憶體 BIN 中找不到 ASCII 文字。"),
            HexEditorInvalidAsciiSearchDetail = Pick("Enter printable ASCII text to search.", "請輸入可顯示的 ASCII 文字。"),
            HexEditorAsciiSearchFoundDetail = Pick("{0}Match {1}/{2} at {3}", "{0}第 {1}/{2} 筆：{3}"),
            HexEditorAsciiSearchIndexTemplate = "{0}/{1}",
            HexEditorAsciiSearchWrappedLabel = Pick("Wrapped. ", "已從開頭繼續搜尋。"),
            HexEditorChangeTitle = Pick("Edit region", "編輯區段"),
            HexEditorChangedBlocksLabel = Pick("Edited blocks", "已修改區塊"),
            HexEditorNoChangedBlocksDetail = Pick("Applied changes will appear here for quick navigation.", "套用修改後會列在這裡，方便快速跳轉。"),
            HexEditorChangedBlockSelectedDetail = Pick("Edited block {0}/{1}: {2} to {3}", "修改區塊 {0}/{1}：{2} 至 {3}"),
            HexEditorSelectChangedBlockTooltip = Pick("Jump to the next contiguous edited block", "跳至下一個連續修改區塊"),
            HexEditorChangedBlockValueReasonSingleTemplate = Pick("Value changed at {0}: {1} -> {2}.", "{0} 的值由 {1} 變更為 {2}。"),
            HexEditorChangedBlockValueReasonMultipleTemplate = Pick("{0} values changed; first at {1}: {2} -> {3}.", "共 {0} 個值變更；第一筆位於 {1}：{2} -> {3}。"),
            HexEditorChangedBlockInsertReasonTemplate = Pick("Inserted {0} byte(s) at {1}; following addresses shifted right by {0}.", "在 {1} 插入 {0} bytes；後續位址向右偏移 {0}。"),
            HexEditorChangedBlockDeleteReasonTemplate = Pick("Deleted {0} byte(s) at {1}; following addresses shifted left by {0}.", "在 {1} 刪除 {0} bytes；後續位址向左偏移 {0}。"),
            HexEditorChangedBlockReasonFallback = Pick("The current memory bytes differ from the opened BIN in this range.", "此範圍的記憶體內容與開啟的 BIN 不同。"),
            HexEditorAddressColumnLabel = Pick("Address", "位址"),
            HexEditorAsciiColumnLabel = "ASCII",
            HexEditorDocumentScrollBarAutomationName = Pick("Hex document scroll bar", "Hex 文件捲軸"),
            HexEditorShowOriginalRowsLabel = Pick("Show original rows", "顯示原始列"),
            HexEditorHexBytesLabel = "Hex bytes",
            HexEditorWriteModeLabel = Pick("Write mode", "寫入模式"),
            HexEditorOverwriteModeLabel = Pick("Overwrite", "覆寫"),
            HexEditorFillModeLabel = Pick("Fill", "填滿"),
            HexEditorOverwriteModeTooltip = Pick("Write supplied bytes from Start. The sequence must end at or before End.", "由 Start 起依序覆寫輸入 bytes，最後一個 byte 不得超過 End。"),
            HexEditorFillModeTooltip = Pick("Repeat one entered byte across the entire selected range.", "將單一輸入 byte 重複寫滿整個所選範圍。"),
            HexEditorOverwriteGuidance = Pick("Writes supplied bytes from Start. They may be shorter than the selection, but never pass End.", "由 Start 起依序覆寫輸入的 bytes；可少於選取範圍，但不得超過 End。"),
            HexEditorFillGuidance = Pick("Repeats one byte across every address from Start through End.", "以單一 byte 填滿 Start 至 End 的所有位址。"),
            HexEditorApplyChangeLabel = Pick("Apply change", "套用修改"),
            HexEditorHexBytesPlaceholder = Pick("A5 5A or FF", "A5 5A 或 FF"),
            HexEditorUndoLabel = Pick("Undo", "復原"),
            HexEditorRedoLabel = Pick("Redo", "重做"),
            HexEditorUndoTooltip = Pick("Undo the latest in-memory edit (Ctrl+Z).", "復原上一筆記憶體修改（Ctrl+Z）。"),
            HexEditorRedoTooltip = Pick("Redo the latest reverted edit (Ctrl+Y).", "重做上一筆已復原的修改（Ctrl+Y）。"),
            HexEditorSaveAsTooltip = Pick("Export the in-memory work copy as a new BIN.", "將記憶體工作副本輸出成新的 BIN。"),
            HexEditorEditByteLabel = Pick("Edit byte", "編輯 byte"),
            HexEditorInvalidAddressDetail = Pick("Enter an in-range hexadecimal address in 0xABCDEF format.", "請以 0xABCDEF 格式輸入有效且在範圍內的十六進位位址。"),
            HexEditorInvalidByteDetail = Pick("Enter exactly one hexadecimal byte, for example A5.", "請輸入一個十六進位 byte，例如 A5。"),
            HexEditorInvalidRangeDetail = Pick("Start and End must define an in-range inclusive selection.", "Start 與 End 必須形成 BIN 內有效的含頭含尾範圍。"),
            HexEditorInputExceedsRangeDetail = Pick("Too many bytes for this selection. Overwrite starts at Start and must end at or before End.", "輸入 bytes 太多：覆寫會從 Start 開始，最後一個 byte 不得超過 End。"),
            HexEditorInvalidByteCountDetail = Pick("Byte count must be within the supported insert limit.", "Byte 數量必須位於支援的插入上限內。"),
            HexEditorInsertBytesBeforeTitle = Pick("Insert bytes before", "在前方插入 bytes"),
            HexEditorInsertBytesAfterTitle = Pick("Insert bytes after", "在後方插入 bytes"),
            HexEditorInsertBytesDetail = Pick("Insert zero-filled bytes into the memory copy. Later addresses shift; the source BIN stays unchanged.", "將 0x00 bytes 插入記憶體副本；後續位址會偏移，來源 BIN 不會被修改。"),
            HexEditorInsertByteCountLabel = Pick("Byte count", "Byte 數量"),
            HexEditorInsertBytesMaximumTemplate = Pick("Allowed range: 1 to {0:N0} bytes", "允許範圍：1 至 {0:N0} bytes"),
            HexEditorInsertBytesActionLabel = Pick("Insert bytes", "插入 bytes"),
        };
    }
}

#pragma warning restore CS1591
