// Resource bags intentionally expose many concise bindable labels; XML comments on each label add noise.
#pragma warning disable CS1591

namespace NvtFwCombiner.Presentation.Avalonia.ViewModels;

public sealed partial class ShellTextResources
{
    private static ShellTextResources CreateEnglish()
    {
        return new ShellTextResources
        {
            Language = ShellLanguage.English,
            HomeLabel = "Home",
            WorkspaceTitle = "Merge / Replace workspace",
            WorkspaceSummary = "Production-backed shell with built-in profiles, flash-map catalog, and report review.",
            PreviewActionLabel = "Preview",
            BuildActionLabel = "Build",
            ReportModalActionLabel = "Report",
            DeviceContextTitle = "Device context",
            IcLabel = "IC",
            NumberLabel = "Number",
            DeviceContextStatus = "refresh profile, slots, validation",
            SettingsPreview = new PlanningCardText(
                "Settings",
                "Configure the app before running firmware workflows.",
                [
                    "Catalog and profile status",
                    "Tool binding and report access",
                    "Theme, strictness, and language preference",
                ],
                "Production-backed settings"),
            MergePreview = new PlanningCardText(
                "Merge",
                "Standard Merge workflow.",
                [
                    "Profile: built-in Standard Merge",
                    "Slots: DP, TP, optional LD",
                    "950/951 DP Perspective policy",
                ],
                "Build wired"),
            ReplacePreview = new PlanningCardText(
                "Replace",
                "DP, CtrlRAM, and General policies.",
                [
                    "Device context: shared IC and Number",
                    "DP Replace includes separate DP and LD payloads",
                    "CtrlRAM Replace uses approved CtrlRAM regions",
                    "CRC/header: combiner.exe postbuild core",
                ],
                "Build wired; CtrlRAM postbuild enabled"),
            FooterStatus = "Profile catalog: built-in | Merge build: wired | Replace build wired; CtrlRAM postbuild enabled | Settings: catalog-backed",
            InitialRunTitle = "No run yet",
            InitialRunDetail = "Drop required BIN files, then run Build.",
            NoOutputLabel = "No output",
            ConfigureKicker = "CONFIGURE",
            WorkflowKicker = "WORKFLOW",
            OpenSettingsLabel = "Open settings",
            OpenLabel = "Open",
            PendingLabel = "Pending",
            LoadJsonLabel = "Load JSON",
            LoadJsonTooltip = "Load report JSON",
            BackTooltip = "Back",
            ModeLabel = "Mode",
            TargetsLabel = "Targets",
            ReviewReplacementInputsTooltip = "Review selected replacement inputs",
            InputFilesTitle = "Input files",
            OutputLayoutTitle = "Output layout",
            PlanTitle = "Plan",
            ValidationTitle = "Validation",
            GeneralReplaceMappingTitle = "General replace mapping",
            GeneralMergeMappingTitle = "General merge mapping",
            ExplicitMappingsTitle = "Explicit mappings",
            AddRangeLabel = "+ Add range",
            AddMappingLabel = "+ Add mapping",
            StartLabel = "Start",
            EndLabel = "End",
            SourceStartLabel = "Source start",
            TargetStartLabel = "Target start",
            LengthLabel = "Length",
            SourceBinLabel = "Source BIN",
            ReplacementBinLabel = "Replacement BIN",
            OutputLengthLabel = "Output length",
            OutputLengthPlaceholder = "0x...",
            BrowseLabel = "Browse",
            RequiredLabel = "Required",
            OptionalLabel = "Optional",
            NoBinSelectedLabel = "No BIN selected",
            MergeDpSlotDescription = "Display payload for Standard Merge",
            MergeTpSlotDescription = "Touch payload for Standard Merge",
            MergeLdSlotDescription = "Required only when the selected profile uses LD",
            BaseFlashBinTitle = "Base flash BIN",
            BaseFlashBinDescription = "Reference firmware image before replacement",
            DpReplacementBinTitle = "DP replacement BIN",
            DpReplacementBinDescription = "Replacement DP is padded to the selected base BIN length; original TP range is restored from base.",
            TpReplacementBinTitle = "TP replacement BIN",
            TpReplacementBinDescription = "Replacement TP input for approved touch/CRC refresh workflows.",
            LdReplacementBinTitle = "LD replacement BIN",
            LdReplacementBinDescription = "Optional LD payload for ICs whose DP Replace profile exposes LD.",
            CtrlRamReplacementBinDescription = "CtrlRAM region replacement; empty slots stay from base.",
            SelectReplacementBinTooltip = "Select replacement BIN",
            SelectSourceBinTooltip = "Select source BIN",
            RemoveRangeTooltip = "Remove range",
            RemoveMappingTooltip = "Remove mapping",
            GeneralReplaceRuleBaseTitle = "Base image",
            GeneralReplaceRuleBaseDetail = "Unmapped bytes stay from the selected base BIN.",
            GeneralReplaceRuleBoundsTitle = "Target bounds",
            GeneralReplaceRuleBoundsDetail = "Ranges must fit the base image and avoid protected regions.",
            GeneralReplaceRuleLengthTitle = "Input length",
            GeneralReplaceRuleLengthDetail = "Replacement BIN data must cover the mapped range length.",
            GeneralReplaceValidationDetail = "Validated execution uses compiled explicit mappings; TP ranges require approved Combiner CRC/header refresh.",
            GeneralReplaceMappingsDetail = "Each row maps one inclusive target range to one replacement BIN.",
            GeneralMergeMappingDetail = "Copy explicit source BIN ranges into a blank output image. No postbuild command runs.",
            GeneralMergeMappingsDetail = "Each row copies one source BIN range to one output target range.",
            CtrlRamInputFilesDetail = "Drop files only for CtrlRAM areas you want to change. Empty areas stay from the base firmware.",
            AbCodeMergeTitle = "AB Code Merge",
            AbCodeMergeDetail = "Reserved until the dedicated AB Code profile and TP CRC/start-address behavior are approved.",
            SettingsCatalogTitle = "Catalog",
            SettingsCatalogSubtitle = "Profile and flash-map status from application catalogs.",
            SettingsRuntimeChecksTitle = "Runtime checks",
            SettingsRuntimeChecksSubtitle = "Packaged validation and header refresh readiness.",
            SettingsDiagnosticsTitle = "Diagnostics",
            SettingsDiagnosticsSubtitle = "Report review and non-execution diagnostics access.",
            SettingsPreferencesTitle = "Preferences",
            SettingsPreferencesSubtitle = "Local shell preferences are saved and restored on startup.",
            ThemeLabel = "Theme",
            StrictnessLabel = "Review strictness",
            LanguageLabel = "Language",
            SettingsInspectorKicker = "INSPECTOR",
            SettingsReadinessTitle = "Settings readiness",
            ReportToastTitle = "Report",
            ReplaceSelectionTitle = "Replace selection",
            CloseSelectionTooltip = "Close selection overview",
            SelectedReplacementsTitle = "Selected replacements",
            RequiredBeforeBuildTitle = "Required before Build",
            CloseLabel = "Close",
            SaveReportLabel = "Save report",
            CloseReportTooltip = "Close report",
            ReportHistoryTitle = "Report history",
            BackToReportLabel = "Back to report",
            ClearAllLabel = "Clear all",
            ClearHistoryLabel = "Clear history",
            ClearHistoryTooltip = "Clear all report history (Ctrl+Shift+Delete)",
            NoReportHistoryLabel = "No report history.",
            RunLabel = "Run",
            OutputLabel = "Output",
            RunResultReportReadyLabel = "report ready",
            ChangeReviewTitle = "Change review",
            EvidenceTitle = "Audit details",
            TraceLabel = "trace",
            OpenReportHistoryTooltip = "Open report history (Ctrl+H)",
            OpenReportHistoryAutomationName = "Open report history",
            ReportTabInputs = "Inputs",
            ReportTabChanges = "Changes",
            ReportTabOperations = "Operations",
            ReportTabPostbuild = "Postbuild",
            ReportTabIssues = "Issues",
            ReportTabRaw = "Raw",
            RunMetadataTitle = "Run metadata",
            ReportFileLabel = "Report file",
            StatusLabel = "Status",
            ArtifactPathLabel = "Artifact path",
            InputsAndHashesTitle = "Input files",
            EmptyInputsMessage = "No input artifact rows were recorded in this report.",
            EmptyByteChangesMessage = "No output differences or changed ranges were recorded.",
            OutputChangesTitle = "Output changes",
            DiffLabel = "Diff",
            RangeLabel = "Range",
            ResultLabel = "Result",
            DetailLabel = "Detail",
            ExplanationLabel = "Explanation",
            ReasonLabel = "Reason",
            ChangedRangesTitle = "Changed ranges",
            EmptyOperationsMessage = "No copy/process operation steps were recorded.",
            OperationStepsTitle = "Operation steps",
            StepLabel = "Step",
            KindLabel = "Kind",
            SourceLabel = "Source",
            TargetLabel = "Target",
            ProcessorLabel = "Processor",
            EmptyPostbuildMessage = "No external postbuild/header refresh command was recorded.",
            HeaderRefreshTraceTitle = "Header refresh trace",
            EmptyIssuesMessage = "No issues or warnings were recorded.",
            IssuesAndWarningsTitle = "Issues and warnings",
            RangeTableTitle = "Range table",
            AddressSpaceLabel = "Address space",
            CommandArgvLabel = "Command argv",
            DeleteReportTooltip = "Delete this report",
            MergeModeTooltip = "Select Standard, reserved AB Code, or high-freedom General Merge.",
        };
    }
}

#pragma warning restore CS1591
