// Resource bags intentionally expose many concise bindable labels; XML comments on each label add noise.
#pragma warning disable CS1591

namespace NvtFwCombiner.Presentation.Avalonia.ViewModels;

public sealed partial class ShellTextResources
{
    private static ShellTextResources CreateEnglish()
    {
        return new ShellTextResources
        {
            Language = ShellLanguage.English,
            HomeLabel = "Home",
            WorkspaceTitle = "Merge / Replace workspace",
            WorkspaceSummary = "Production-backed shell with built-in profiles, flash-map catalog, and report review.",
            PreviewActionLabel = "Preview",
            BuildActionLabel = "Build",
            ReportModalActionLabel = "Report",
            DeviceContextTitle = "Device context",
            IcLabel = "IC",
            NumberLabel = "Number",
            DeviceContextStatus = "refresh profile, slots, validation",
            SettingsPreview = new PlanningCardText(
                "Settings",
                "Configure the app before running firmware workflows.",
                [
                    "Catalog and profile status",
                    "Tool binding and report access",
                    "Theme, strictness, and language preference",
                ],
                "Production-backed settings"),
            MergePreview = new PlanningCardText(
                "Merge",
                "Standard Merge workflow.",
                [
                    "Profile: built-in Standard Merge",
                    "Slots: DP, TP, optional LD",
                    "950/951 DP Perspective policy",
                ],
                "Build wired"),
            ReplacePreview = new PlanningCardText(
                "Replace",
                "DP, CtrlRAM, and General policies.",
                [
                    "Device context: shared IC and Number",
                    "DP Replace includes separate DP and LD payloads",
                    "CtrlRAM Replace uses approved CtrlRAM regions",
                    "CRC/header: combiner.exe postbuild core",
                ],
                "Build wired; CtrlRAM postbuild enabled"),
            InitialRunTitle = "No run yet",
            InitialRunDetail = "Drop required BIN files, then run Build.",
            NoOutputLabel = "No output",
            WorkflowKicker = "WORKFLOW",
            OpenLabel = "Open",
            PendingLabel = "Pending",
            LoadJsonLabel = "Load JSON",
            LoadJsonTooltip = "Load report JSON",
            BackTooltip = "Back",
            ModeLabel = "Mode",
            TargetsLabel = "Targets",
            ReviewReplacementInputsTooltip = "Review selected replacement inputs",
            InputFilesTitle = "Input files",
            OutputLayoutTitle = "Output layout",
            PlanTitle = "Plan",
            ValidationTitle = "Validation",
            GeneralReplaceMappingTitle = "General replace mapping",
            GeneralMergeMappingTitle = "General merge mapping",
            ExplicitMappingsTitle = "Explicit mappings",
            AddRangeLabel = "+ Add range",
            AddMappingLabel = "+ Add mapping",
            StartLabel = "Start",
            EndLabel = "End",
            SourceStartLabel = "Source start",
            TargetStartLabel = "Target start",
            LengthLabel = "Length",
            SourceBinLabel = "Source BIN",
            ReplacementBinLabel = "Replacement BIN",
            OutputLengthLabel = "Output length",
            OutputLengthPlaceholder = "0x...",
            BrowseLabel = "Browse",
            RequiredLabel = "Required",
            OptionalLabel = "Optional",
            NoBinSelectedLabel = "No BIN selected",
            MergeDpSlotDescription = "Display payload for Standard Merge",
            MergeTpSlotDescription = "Touch payload for Standard Merge",
            MergeLdSlotDescription = "Required only when the selected profile uses LD",
            BaseFlashBinTitle = "Base firmware BIN",
            BaseFlashBinDescription = "Reference firmware image before replacement",
            DpReplacementBinTitle = "DP replacement BIN",
            DpReplacementBinDescription = "Replacement DP is padded to the selected base BIN length; original TP range is restored from base.",
            SelectReplacementBinTooltip = "Select replacement BIN",
            SelectSourceBinTooltip = "Select source BIN",
            RemoveRangeTooltip = "Remove range",
            RemoveMappingTooltip = "Remove mapping",
            GeneralReplaceRuleBaseTitle = "Base image",
            GeneralReplaceRuleBaseDetail = "Unmapped bytes stay from the selected base BIN.",
            GeneralReplaceRuleBoundsTitle = "Target bounds",
            GeneralReplaceRuleBoundsDetail = "Ranges must fit the base image and avoid protected regions.",
            GeneralReplaceRuleLengthTitle = "Input length",
            GeneralReplaceRuleLengthDetail = "Replacement BIN data must cover the mapped range length.",
            GeneralReplaceValidationDetail = "Validated execution uses compiled explicit mappings; TP ranges require approved Combiner CRC/header refresh.",
            GeneralReplaceMappingsDetail = "Each row maps one inclusive target range to one replacement BIN.",
            HexEditorSaveAsLabel = "Save as...",
            HexEditorSaveConfirmationTitle = "Save new BIN?",
            HexEditorSaveConfirmationDetail = "Edits remain in memory until export. Save As writes a new BIN only; it never changes the opened source BIN and does not run firmware validation or postbuild.",
            HexEditorSaveConfirmationActionLabel = "Choose output",
            GeneralMergeMappingDetail = "Copy explicit source BIN ranges into a blank output image. No postbuild command runs.",
            GeneralMergeMappingsDetail = "Each row copies one source BIN range to one output target range.",
            CtrlRamInputFilesDetail = "When the selected IC/profile supports it, use TP FW or a complete Flash Code as the base firmware BIN. Drop files only for CtrlRAM areas you want to change; empty areas stay from the base firmware.",
            CtrlRamFirmwareVersionTitle = "TP version for this output",
            CtrlRamFirmwareVersionDetail = "Choose how the output version is prepared before the approved CtrlRAM postbuild runs.",
            CtrlRamFirmwareVersionKeepLabel = "✓  Keep base version",
            CtrlRamFirmwareVersionEditLabel = "✎  Set a new version",
            CtrlRamFirmwareVersionCurrentLabel = "Base firmware TP version",
            CtrlRamFirmwareVersionByteLabel = "FW version",
            CtrlRamFirmwareSubVersionByteLabel = "FW sub-version",
            CtrlRamFirmwareVersionSourceDetail = "Read from the verified NVT Backup in the base firmware. Postbuild propagates the chosen value to the output Backup.",
            CtrlRamFirmwareVersionEditUnavailableDetail = "The NVT Backup version metadata is unavailable or invalid, so only keeping the original version is allowed.",
            CtrlRamFirmwareVersionInvalidByteDetail = "Enter each version field as one hexadecimal byte from 00 to FF.",
            CtrlRamFirmwareVersionChooseOutputLabel = "Continue to output",
            AbCodeMergeTitle = "AB Code Merge",
            AbCodeMergeDetail = "Reserved until the dedicated AB Code profile and TP CRC/start-address behavior are approved.",
            SettingsCatalogTitle = "Catalog",
            SettingsCatalogSubtitle = "Profile and flash-map status from application catalogs.",
            SettingsRuntimeChecksTitle = "Runtime checks",
            SettingsRuntimeChecksSubtitle = "Packaged validation and header refresh readiness.",
            SettingsDiagnosticsTitle = "Diagnostics",
            SettingsDiagnosticsSubtitle = "Report review and non-execution diagnostics access.",
            SettingsPreferencesTitle = "Preferences",
            SettingsPreferencesSubtitle = "Local shell preferences are saved and restored on startup.",
            ThemeLabel = "Theme",
            StrictnessLabel = "Review strictness",
            LanguageLabel = "Language",
            SettingsInspectorKicker = "INSPECTOR",
            SettingsReadinessTitle = "Settings readiness",
            ReportToastTitle = "Report",
            ReplaceSelectionTitle = "Replace selection",
            CloseSelectionTooltip = "Close selection overview",
            SelectedReplacementsTitle = "Selected replacements",
            RequiredBeforeBuildTitle = "Required before Build",
            CloseLabel = "Close",
            SaveReportLabel = "Save report",
            CloseReportTooltip = "Close report",
            ReportHistoryTitle = "Report history",
            BackToReportLabel = "Back to report",
            ClearAllLabel = "Clear all",
            ClearHistoryLabel = "Clear history",
            ClearHistoryTooltip = "Clear all report history (Ctrl+Shift+Delete)",
            NoReportHistoryLabel = "No report history.",
            RunLabel = "Run",
            OutputLabel = "Output",
            RunResultReportReadyLabel = "report ready",
            ChangeReviewTitle = "Change review",
            EvidenceTitle = "Audit details",
            TraceLabel = "trace",
            OpenReportHistoryTooltip = "Open report history (Ctrl+H)",
            OpenReportHistoryAutomationName = "Open report history",
            ReportTabInputs = "Inputs",
            ReportTabChanges = "Changes",
            ReportTabOperations = "Operations",
            ReportTabPostbuild = "Postbuild",
            ReportTabIssues = "Issues",
            ReportTabRaw = "Raw",
            RawReportTitle = "Raw report JSON",
            RawReportDetail = "Audit-only source data. Use the other tabs for normal review.",
            RunMetadataTitle = "Run metadata",
            ReportFileLabel = "Report file",
            FileLabel = "File",
            SizeLabel = "Size",
            StateLabel = "State",
            StatusLabel = "Status",
            ArtifactPathLabel = "Artifact path",
            InputsAndHashesTitle = "Input files",
            EmptyInputsMessage = "No input artifact rows were recorded in this report.",
            EmptyByteChangesMessage = "No output differences or changed ranges were recorded.",
            OutputChangesTitle = "Output changes",
            RangeLabel = "Range",
            ResultLabel = "Result",
            DetailLabel = "Detail",
            ChangedRangesTitle = "Changed ranges",
            EmptyOperationsMessage = "No copy/process operation steps were recorded.",
            OperationStepsTitle = "Operation steps",
            KindLabel = "Kind",
            SourceLabel = "Source",
            EmptyPostbuildMessage = "No external postbuild/header refresh command was recorded.",
            HeaderRefreshTraceTitle = "Header refresh trace",
            EmptyIssuesMessage = "No issues or warnings were recorded.",
            NoActionRequiredTitle = "No action required",
            IssuesAndWarningsTitle = "Issues and warnings",
            RangeTableTitle = "Range table",
            AddressSpaceLabel = "Address space",
            CopyCommandTooltip = "Copy command evidence",
            DeleteReportTooltip = "Delete this report",
            MergeModeTooltip = "Select Standard, reserved AB Code, or high-freedom General Merge.",
            WorkflowContextReplaceDetail = "Choose the IC and IC count before opening Replace. You can change them later from the shared context row.",
            WorkflowContextMergeDetail = "Choose the IC before opening Merge. IC count is not part of the Standard or General Merge authoring context.",
            WorkflowContextSafetyDetail = "This only selects the catalog context. It does not inspect, modify, or write any firmware file.",
            FirmwareIcMismatchTitle = "Selected BIN suggests another IC",
            FirmwareIcMismatchDetail = "A marker found in the file name or printable header text differs from the current catalog context. This is a prompt only; it does not validate the BIN or change it.",
            FirmwareIcMismatchCurrentLabel = "Current IC",
            FirmwareIcMismatchDetectedLabel = "Detected marker",
            FirmwareIcMismatchKeepLabel = "Keep current IC",
            FirmwareIcMismatchUseDetectedLabel = "Use detected IC",
            ContextUpdatedToastTitle = "Context updated",
            UtilToolsLabel = "UTIL",
            UtilToolsHomeTitle = "Tool",
            UtilToolsHomeDetail = "Inspect and edit raw BIN files.",
            HexEditorContextInsertZeroBeforeLabel = "Insert 00 before this byte",
            HexEditorContextInsertZeroAfterLabel = "Insert 00 after this byte",
            HexEditorContextInsertBytesBeforeLabel = "Insert N bytes before...",
            HexEditorContextInsertBytesAfterLabel = "Insert N bytes after...",
            HexEditorContextDeleteByteLabel = "Delete this byte (shift later bytes left)",
            HexEditorContextSetToZeroLabel = "Set this byte to 00",
            HexEditorContextSetToFfLabel = "Set this byte to FF",
            HexEditorContextGoToBlockStartLabel = "Go to block start",
            HexEditorContextGoToBlockEndLabel = "Go to block end",
            HexEditorSourceReadyDetail = "In memory: 0x{0:X} bytes | {1} edit(s)",
            HexEditorSourceEmptyDetail = "Open a BIN to inspect and edit a private in-memory work copy.",
            HexEditorSaveCompletedDetail = "Saved a new BIN: {0}",
            HexEditorFileOperationFailedDetail = "The BIN operation could not be completed.",
            HexEditorNothingToUndoDetail = "There is no in-memory change to undo.",
            HexEditorNothingToRedoDetail = "There is no reverted change to redo.",
            HexEditorTitle = "Hex Editor",
            HexEditorDetail = "Raw BIN utility. Edit an in-memory work copy, then Save As a new BIN. No IC, profile, CRC, or postbuild rule is applied.",
            HexEditorGoToAddressLabel = "Go to address",
            HexEditorAsciiSearchLabel = "Find ASCII",
            HexEditorAsciiSearchPlaceholder = "Find ASCII",
            HexEditorAsciiSearchNotFoundDetail = "ASCII text was not found in the in-memory BIN.",
            HexEditorInvalidAsciiSearchDetail = "Enter printable ASCII text to search.",
            HexEditorAsciiSearchFoundDetail = "{0}Match {1}/{2} at {3}",
            HexEditorAsciiSearchIndexTemplate = "{0}/{1}",
            HexEditorAsciiSearchWrappedLabel = "Wrapped. ",
            HexEditorChangeTitle = "Edit region",
            HexEditorChangedBlocksLabel = "Edited blocks",
            HexEditorNoChangedBlocksDetail = "Applied changes will appear here for quick navigation.",
            HexEditorChangedBlockSelectedDetail = "Edited block {0}/{1}: {2} to {3}",
            HexEditorSelectChangedBlockTooltip = "Jump to the next contiguous edited block",
            HexEditorChangedBlockValueReasonSingleTemplate = "Value changed at {0}: {1} -> {2}.",
            HexEditorChangedBlockValueReasonMultipleTemplate = "{0} values changed; first at {1}: {2} -> {3}.",
            HexEditorChangedBlockInsertReasonTemplate = "Inserted {0} byte(s) at {1}; following addresses shifted right by {0}.",
            HexEditorChangedBlockDeleteReasonTemplate = "Deleted {0} byte(s) at {1}; following addresses shifted left by {0}.",
            HexEditorChangedBlockReasonFallback = "The current memory bytes differ from the opened BIN in this range.",
            HexEditorAddressColumnLabel = "Address",
            HexEditorAsciiColumnLabel = "ASCII",
            HexEditorDocumentScrollBarAutomationName = "Hex document scroll bar",
            HexEditorShowOriginalRowsLabel = "Show original rows",
            HexEditorHexBytesLabel = "Hex bytes",
            HexEditorWriteModeLabel = "Write mode",
            HexEditorOverwriteModeLabel = "Overwrite",
            HexEditorFillModeLabel = "Fill",
            HexEditorOverwriteModeTooltip = "Write supplied bytes from Start. The sequence must end at or before End.",
            HexEditorFillModeTooltip = "Repeat one entered byte across the entire selected range.",
            HexEditorOverwriteGuidance = "Writes supplied bytes from Start. They may be shorter than the selection, but never pass End.",
            HexEditorFillGuidance = "Repeats one byte across every address from Start through End.",
            HexEditorApplyChangeLabel = "Apply change",
            HexEditorHexBytesPlaceholder = "A5 5A or FF",
            HexEditorUndoLabel = "Undo",
            HexEditorRedoLabel = "Redo",
            HexEditorUndoTooltip = "Undo the latest in-memory edit (Ctrl+Z).",
            HexEditorRedoTooltip = "Redo the latest reverted edit (Ctrl+Y).",
            HexEditorSaveAsTooltip = "Export the in-memory work copy as a new BIN.",
            HexEditorEditByteLabel = "Edit byte",
            HexEditorInvalidAddressDetail = "Enter an in-range hexadecimal address in 0xABCDEF format.",
            HexEditorInvalidByteDetail = "Enter exactly one hexadecimal byte, for example A5.",
            HexEditorInvalidRangeDetail = "Start and End must define an in-range inclusive selection.",
            HexEditorInputExceedsRangeDetail = "Too many bytes for this selection. Overwrite starts at Start and must end at or before End.",
            HexEditorInvalidByteCountDetail = "Byte count must be within the supported insert limit.",
            HexEditorInsertBytesBeforeTitle = "Insert bytes before",
            HexEditorInsertBytesAfterTitle = "Insert bytes after",
            HexEditorInsertBytesDetail = "Insert zero-filled bytes into the memory copy. Later addresses shift; the source BIN stays unchanged.",
            HexEditorInsertByteCountLabel = "Byte count",
            HexEditorInsertBytesMaximumTemplate = "Allowed range: 1 to {0:N0} bytes",
            HexEditorInsertBytesActionLabel = "Insert bytes",
        };
    }
}

#pragma warning restore CS1591
