// Resource bags intentionally expose many concise bindable labels; XML comments on each label add noise.
#pragma warning disable CS1591

namespace NvtFwCombiner.Presentation.Avalonia.ViewModels;

public sealed partial class ShellTextResources
{
    private static ShellTextResources CreateChineseTraditional()
    {
        return new ShellTextResources
        {
            Language = ShellLanguage.ChineseTraditional,
            HomeLabel = "首頁",
            WorkspaceTitle = "合併 / 取代工作區",
            WorkspaceSummary = "使用內建 profile、flash-map catalog 與 report review 的生產導向介面。",
            PreviewActionLabel = "預覽",
            BuildActionLabel = "建立",
            ReportModalActionLabel = "Report",
            DeviceContextTitle = "裝置條件",
            IcLabel = "IC",
            NumberLabel = "數量",
            DeviceContextStatus = "刷新 profile、slot、validation",
            SettingsPreview = new PlanningCardText(
                "設定",
                "執行韌體流程前的 app 設定。",
                [
                    "Catalog 與 profile 狀態",
                    "Tool binding 與 report 存取",
                    "主題、審查嚴格度與語言偏好",
                ],
                "生產資料支援的設定"),
            MergePreview = new PlanningCardText(
                "合併",
                "Standard Merge 流程。",
                [
                    "Profile：內建 Standard Merge",
                    "Slots：DP、TP、選用 LD",
                    "950/951 DP Perspective policy",
                ],
                "Build 已串接"),
            ReplacePreview = new PlanningCardText(
                "取代",
                "DP、CtrlRAM 與 General policy。",
                [
                    "裝置條件：共用 IC 與數量",
                    "DP Replace 包含分開的 DP 與 LD payload",
                    "CtrlRAM Replace 使用核准的 CtrlRAM regions",
                    "CRC/header：combiner.exe postbuild core",
                ],
                "Build 已串接；CtrlRAM postbuild 已啟用"),
            InitialRunTitle = "尚未執行",
            InitialRunDetail = "放入必要 BIN 檔後即可建立。",
            NoOutputLabel = "無輸出",
            WorkflowKicker = "流程",
            OpenLabel = "開啟",
            PendingLabel = "待實作",
            LoadJsonLabel = "載入 JSON",
            LoadJsonTooltip = "載入 report JSON",
            BackTooltip = "返回",
            ModeLabel = "模式",
            TargetsLabel = "目標",
            ReviewReplacementInputsTooltip = "查看已選擇的 replacement inputs",
            InputFilesTitle = "輸入檔案",
            OutputLayoutTitle = "輸出配置",
            PlanTitle = "計畫",
            ValidationTitle = "驗證",
            GeneralReplaceMappingTitle = "General replace mapping",
            GeneralMergeMappingTitle = "General merge mapping",
            ExplicitMappingsTitle = "明確 mappings",
            AddRangeLabel = "+ 新增範圍",
            AddMappingLabel = "+ 新增 mapping",
            StartLabel = "起始",
            EndLabel = "結束",
            SourceStartLabel = "來源起始",
            TargetStartLabel = "目標起始",
            LengthLabel = "長度",
            SourceBinLabel = "Source BIN",
            ReplacementBinLabel = "Replacement BIN",
            OutputLengthLabel = "輸出長度",
            OutputLengthPlaceholder = "0x...",
            BrowseLabel = "瀏覽",
            RequiredLabel = "必填",
            OptionalLabel = "選填",
            NoBinSelectedLabel = "尚未選擇 BIN",
            MergeDpSlotDescription = "Standard Merge 的 Display payload",
            MergeTpSlotDescription = "Standard Merge 的 Touch payload",
            MergeLdSlotDescription = "只有選定 profile 使用 LD 時才需要",
            BaseFlashBinTitle = "Base firmware BIN",
            BaseFlashBinDescription = "取代前的參考韌體映像",
            DpReplacementBinTitle = "DP replacement BIN",
            DpReplacementBinDescription = "DP replacement 會依 base BIN 長度處理；原 TP 範圍會從 base 還原。",
            SelectReplacementBinTooltip = "選擇 replacement BIN",
            SelectSourceBinTooltip = "選擇 source BIN",
            RemoveRangeTooltip = "移除範圍",
            RemoveMappingTooltip = "移除 mapping",
            GeneralReplaceRuleBaseTitle = "Base image",
            GeneralReplaceRuleBaseDetail = "未 mapping 的 bytes 會保留選定 base BIN 的內容。",
            GeneralReplaceRuleBoundsTitle = "目標邊界",
            GeneralReplaceRuleBoundsDetail = "範圍必須落在 base image 內並避開 protected regions。",
            GeneralReplaceRuleLengthTitle = "輸入長度",
            GeneralReplaceRuleLengthDetail = "Replacement BIN data 必須覆蓋 mapping 範圍長度。",
            GeneralReplaceValidationDetail = "執行時會使用已編譯的 explicit mappings；TP 範圍需要核准的 Combiner CRC/header refresh。",
            GeneralReplaceMappingsDetail = "每列將一個 inclusive target range 對應到一個 replacement BIN。",
            HexEditorSaveAsLabel = "另存新檔...",
            HexEditorSaveConfirmationTitle = "儲存新的 BIN？",
            HexEditorSaveConfirmationDetail = "修改只保留在記憶體直到輸出。另存新檔只會寫出新的 BIN，絕不改寫已開啟來源，且不會執行韌體驗證或 postbuild。",
            HexEditorSaveConfirmationActionLabel = "選擇輸出位置",
            GeneralMergeMappingDetail = "將明確 source BIN ranges 複製到 blank output image；不執行 postbuild command。",
            GeneralMergeMappingsDetail = "每列將一個 source BIN range 複製到一個 output target range。",
            CtrlRamInputFilesDetail = "Base firmware BIN 可使用 TP FW 或完整 Flash Code。只放入要更動的 CtrlRAM 區域檔案；未放入的區域保留 base firmware。",
            CtrlRamFirmwareVersionTitle = "設定這次輸出的 TP 版本",
            CtrlRamFirmwareVersionDetail = "選擇核准的 CtrlRAM postbuild 執行前，要如何準備輸出版本。",
            CtrlRamFirmwareVersionKeepLabel = "✓  沿用 Base 版本",
            CtrlRamFirmwareVersionEditLabel = "✎  設定新版本",
            CtrlRamFirmwareVersionCurrentLabel = "Base firmware 的 TP 版本",
            CtrlRamFirmwareVersionByteLabel = "FW 版本",
            CtrlRamFirmwareSubVersionByteLabel = "FW 子版本",
            CtrlRamFirmwareVersionSourceDetail = "此值取自 base firmware 內已驗證的 NVT Backup；postbuild 會把選定版本帶到輸出 Backup。",
            CtrlRamFirmwareVersionEditUnavailableDetail = "NVT Backup 的版本資訊不存在或驗證失敗，因此只能維持原本版本。",
            CtrlRamFirmwareVersionInvalidByteDetail = "每個版本欄位須輸入 00 到 FF 的一個十六進位 byte。",
            CtrlRamFirmwareVersionChooseOutputLabel = "繼續選擇輸出",
            AbCodeMergeTitle = "AB Code Merge",
            AbCodeMergeDetail = "保留到 dedicated AB Code profile 與 TP CRC/start-address 行為核准後再啟用。",
            SettingsCatalogTitle = "Catalog",
            SettingsCatalogSubtitle = "Application catalog 提供的 profile 與 flash-map 狀態。",
            SettingsRuntimeChecksTitle = "執行檢查",
            SettingsRuntimeChecksSubtitle = "打包好的 validation 與 header refresh readiness。",
            SettingsDiagnosticsTitle = "診斷",
            SettingsDiagnosticsSubtitle = "Report review 與不執行韌體的診斷存取。",
            SettingsPreferencesTitle = "偏好設定",
            SettingsPreferencesSubtitle = "本機 shell 偏好會儲存並在啟動時還原。",
            ThemeLabel = "主題",
            StrictnessLabel = "審查嚴格度",
            LanguageLabel = "語言",
            SettingsInspectorKicker = "檢視",
            SettingsReadinessTitle = "設定狀態",
            ReportToastTitle = "Report",
            ReplaceSelectionTitle = "Replace selection",
            CloseSelectionTooltip = "關閉 selection overview",
            SelectedReplacementsTitle = "已選 replacements",
            RequiredBeforeBuildTitle = "Build 前必填",
            CloseLabel = "關閉",
            SaveReportLabel = "儲存 report",
            CloseReportTooltip = "關閉 report",
            ReportHistoryTitle = "Report history",
            BackToReportLabel = "回到 report",
            ClearAllLabel = "全部清除",
            ClearHistoryLabel = "清除 history",
            ClearHistoryTooltip = "清除全部 report history (Ctrl+Shift+Delete)",
            NoReportHistoryLabel = "目前沒有 report history。",
            RunLabel = "執行",
            OutputLabel = "輸出",
            RunResultReportReadyLabel = "report 已就緒",
            ChangeReviewTitle = "差異審查",
            EvidenceTitle = "審查明細",
            TraceLabel = "trace",
            OpenReportHistoryTooltip = "開啟 report history (Ctrl+H)",
            OpenReportHistoryAutomationName = "開啟 report history",
            ReportTabInputs = "輸入",
            ReportTabChanges = "差異",
            ReportTabOperations = "操作",
            ReportTabPostbuild = "Postbuild",
            ReportTabIssues = "問題",
            ReportTabRaw = "原始資料",
            RawReportTitle = "原始 report JSON",
            RawReportDetail = "僅供稽核與除錯；一般檢視請使用其他分頁。",
            RunMetadataTitle = "執行資訊",
            ReportFileLabel = "Report 檔案",
            FileLabel = "檔案",
            SizeLabel = "大小",
            StateLabel = "狀態",
            StatusLabel = "狀態",
            ArtifactPathLabel = "Artifact path",
            InputsAndHashesTitle = "輸入檔案",
            EmptyInputsMessage = "此 report 沒有記錄 input artifact rows。",
            EmptyByteChangesMessage = "此 report 沒有記錄 output differences 或 changed ranges。",
            OutputChangesTitle = "輸出差異",
            RangeLabel = "範圍",
            ResultLabel = "結果",
            DetailLabel = "細節",
            ChangedRangesTitle = "Changed ranges",
            EmptyOperationsMessage = "此 report 沒有記錄 copy/process operation steps。",
            OperationStepsTitle = "Operation steps",
            KindLabel = "Kind",
            SourceLabel = "Source",
            EmptyPostbuildMessage = "此 report 沒有記錄 external postbuild/header refresh command。",
            HeaderRefreshTraceTitle = "Header refresh trace",
            EmptyIssuesMessage = "此 report 沒有記錄 issues 或 warnings。",
            NoActionRequiredTitle = "不需處理",
            IssuesAndWarningsTitle = "問題與警告",
            RangeTableTitle = "Range table",
            AddressSpaceLabel = "Address space",
            CopyCommandTooltip = "複製命令證據",
            DeleteReportTooltip = "刪除此 report",
            MergeModeTooltip = "選擇 Standard、保留的 AB Code 或高自由度 General Merge。",
            WorkflowContextReplaceDetail = "進入 Replace 前先選擇 IC 與 IC 數量；之後仍可從共用條件列調整。",
            WorkflowContextMergeDetail = "進入 Merge 前先選擇 IC；Standard 與 General Merge 的 authoring context 不使用 IC 數量。",
            WorkflowContextSafetyDetail = "這只會選擇 catalog 條件，不會讀取、修改或寫入任何 firmware 檔案。",
            FirmwareIcMismatchTitle = "選擇的 BIN 顯示另一個 IC",
            FirmwareIcMismatchDetail = "檔名或可讀 header 文字中的 IC marker 與目前 catalog 條件不同。此提示不會驗證或修改 BIN，也不會自動變更 IC。",
            FirmwareIcMismatchCurrentLabel = "目前 IC",
            FirmwareIcMismatchDetectedLabel = "偵測 marker",
            FirmwareIcMismatchKeepLabel = "維持目前 IC",
            FirmwareIcMismatchUseDetectedLabel = "使用偵測到的 IC",
            ContextUpdatedToastTitle = "條件已更新",
            UtilToolsLabel = "工具",
            UtilToolsHomeTitle = "工具",
            UtilToolsHomeDetail = "檢視與編輯原始 BIN。",
            HexEditorContextInsertZeroBeforeLabel = "在此 byte 前插入 00",
            HexEditorContextInsertZeroAfterLabel = "在此 byte 後插入 00",
            HexEditorContextInsertBytesBeforeLabel = "在此 byte 前插入 N bytes...",
            HexEditorContextInsertBytesAfterLabel = "在此 byte 後插入 N bytes...",
            HexEditorContextDeleteByteLabel = "刪除此 byte（後續 byte 左移）",
            HexEditorContextSetToZeroLabel = "將此 byte 設為 00",
            HexEditorContextSetToFfLabel = "將此 byte 設為 FF",
            HexEditorContextGoToBlockStartLabel = "跳至區塊開頭",
            HexEditorContextGoToBlockEndLabel = "跳至區塊結尾",
            HexEditorSourceReadyDetail = "記憶體中：0x{0:X} bytes | {1} 筆修改",
            HexEditorSourceEmptyDetail = "開啟 BIN 後即可在私有記憶體工作副本中檢視與修改。",
            HexEditorSaveCompletedDetail = "已儲存新的 BIN：{0}",
            HexEditorFileOperationFailedDetail = "無法完成 BIN 操作。",
            HexEditorNothingToUndoDetail = "沒有可復原的記憶體修改。",
            HexEditorNothingToRedoDetail = "沒有可重做的修改。",
            HexEditorTitle = "Hex Editor",
            HexEditorDetail = "純 BIN 工具。修改只存在記憶體工作副本，另存新檔才輸出；不套用 IC、profile、CRC 或 postbuild 規則。",
            HexEditorGoToAddressLabel = "跳至位址",
            HexEditorAsciiSearchLabel = "搜尋 ASCII",
            HexEditorAsciiSearchPlaceholder = "搜尋 ASCII",
            HexEditorAsciiSearchNotFoundDetail = "目前記憶體 BIN 中找不到 ASCII 文字。",
            HexEditorInvalidAsciiSearchDetail = "請輸入可顯示的 ASCII 文字。",
            HexEditorAsciiSearchFoundDetail = "{0}第 {1}/{2} 筆：{3}",
            HexEditorAsciiSearchIndexTemplate = "{0}/{1}",
            HexEditorAsciiSearchWrappedLabel = "已從開頭繼續搜尋。",
            HexEditorChangeTitle = "編輯區段",
            HexEditorChangedBlocksLabel = "已修改區塊",
            HexEditorNoChangedBlocksDetail = "套用修改後會列在這裡，方便快速跳轉。",
            HexEditorChangedBlockSelectedDetail = "修改區塊 {0}/{1}：{2} 至 {3}",
            HexEditorSelectChangedBlockTooltip = "跳至下一個連續修改區塊",
            HexEditorChangedBlockValueReasonSingleTemplate = "{0} 的值由 {1} 變更為 {2}。",
            HexEditorChangedBlockValueReasonMultipleTemplate = "共 {0} 個值變更；第一筆位於 {1}：{2} -> {3}。",
            HexEditorChangedBlockInsertReasonTemplate = "在 {1} 插入 {0} bytes；後續位址向右偏移 {0}。",
            HexEditorChangedBlockDeleteReasonTemplate = "在 {1} 刪除 {0} bytes；後續位址向左偏移 {0}。",
            HexEditorChangedBlockReasonFallback = "此範圍的記憶體內容與開啟的 BIN 不同。",
            HexEditorAddressColumnLabel = "位址",
            HexEditorAsciiColumnLabel = "ASCII",
            HexEditorDocumentScrollBarAutomationName = "Hex 文件捲軸",
            HexEditorShowOriginalRowsLabel = "顯示原始列",
            HexEditorHexBytesLabel = "Hex bytes",
            HexEditorWriteModeLabel = "寫入模式",
            HexEditorOverwriteModeLabel = "覆寫",
            HexEditorFillModeLabel = "填滿",
            HexEditorOverwriteModeTooltip = "由 Start 起依序覆寫輸入 bytes，最後一個 byte 不得超過 End。",
            HexEditorFillModeTooltip = "將單一輸入 byte 重複寫滿整個所選範圍。",
            HexEditorOverwriteGuidance = "由 Start 起依序覆寫輸入的 bytes；可少於選取範圍，但不得超過 End。",
            HexEditorFillGuidance = "以單一 byte 填滿 Start 至 End 的所有位址。",
            HexEditorApplyChangeLabel = "套用修改",
            HexEditorHexBytesPlaceholder = "A5 5A 或 FF",
            HexEditorUndoLabel = "復原",
            HexEditorRedoLabel = "重做",
            HexEditorUndoTooltip = "復原上一筆記憶體修改（Ctrl+Z）。",
            HexEditorRedoTooltip = "重做上一筆已復原的修改（Ctrl+Y）。",
            HexEditorSaveAsTooltip = "將記憶體工作副本輸出成新的 BIN。",
            HexEditorEditByteLabel = "編輯 byte",
            HexEditorInvalidAddressDetail = "請以 0xABCDEF 格式輸入有效且在範圍內的十六進位位址。",
            HexEditorInvalidByteDetail = "請輸入一個十六進位 byte，例如 A5。",
            HexEditorInvalidRangeDetail = "Start 與 End 必須形成 BIN 內有效的含頭含尾範圍。",
            HexEditorInputExceedsRangeDetail = "輸入 bytes 太多：覆寫會從 Start 開始，最後一個 byte 不得超過 End。",
            HexEditorInvalidByteCountDetail = "Byte 數量必須位於支援的插入上限內。",
            HexEditorInsertBytesBeforeTitle = "在前方插入 bytes",
            HexEditorInsertBytesAfterTitle = "在後方插入 bytes",
            HexEditorInsertBytesDetail = "將 0x00 bytes 插入記憶體副本；後續位址會偏移，來源 BIN 不會被修改。",
            HexEditorInsertByteCountLabel = "Byte 數量",
            HexEditorInsertBytesMaximumTemplate = "允許範圍：1 至 {0:N0} bytes",
            HexEditorInsertBytesActionLabel = "插入 bytes",
        };
    }
}

#pragma warning restore CS1591
