// Resource bags intentionally expose many concise bindable labels; XML comments on each label add noise.
#pragma warning disable CS1591

namespace NvtFwCombiner.Presentation.Avalonia.ViewModels;

public sealed partial class ShellTextResources
{
    private static ShellTextResources CreateChineseTraditional()
    {
        return new ShellTextResources
        {
            Language = ShellLanguage.ChineseTraditional,
            HomeLabel = "首頁",
            WorkspaceTitle = "合併 / 取代工作區",
            WorkspaceSummary = "使用內建 profile、flash-map catalog 與 report review 的生產導向介面。",
            PreviewActionLabel = "預覽",
            BuildActionLabel = "建立",
            ReportModalActionLabel = "Report",
            DeviceContextTitle = "裝置條件",
            IcLabel = "IC",
            NumberLabel = "數量",
            DeviceContextStatus = "刷新 profile、slot、validation",
            SettingsPreview = new PlanningCardText(
                "設定",
                "執行韌體流程前的 app 設定。",
                [
                    "Catalog 與 profile 狀態",
                    "Tool binding 與 report 存取",
                    "主題、審查嚴格度與語言偏好",
                ],
                "生產資料支援的設定"),
            MergePreview = new PlanningCardText(
                "合併",
                "Standard Merge 流程。",
                [
                    "Profile：內建 Standard Merge",
                    "Slots：DP、TP、選用 LD",
                    "950/951 DP Perspective policy",
                ],
                "Build 已串接"),
            ReplacePreview = new PlanningCardText(
                "取代",
                "DP、CtrlRAM 與 General policy。",
                [
                    "裝置條件：共用 IC 與數量",
                    "DP Replace 包含分開的 DP 與 LD payload",
                    "CtrlRAM Replace 使用核准的 CtrlRAM regions",
                    "CRC/header：combiner.exe postbuild core",
                ],
                "Build 已串接；CtrlRAM postbuild 已啟用"),
            FooterStatus = "Profile catalog：內建 | Merge build：已串接 | Replace build：已串接；CtrlRAM postbuild 已啟用 | Settings：catalog-backed",
            InitialRunTitle = "尚未執行",
            InitialRunDetail = "放入必要 BIN 檔後即可建立。",
            NoOutputLabel = "無輸出",
            ConfigureKicker = "設定",
            WorkflowKicker = "流程",
            OpenSettingsLabel = "開啟設定",
            OpenLabel = "開啟",
            PendingLabel = "待實作",
            LoadJsonLabel = "載入 JSON",
            LoadJsonTooltip = "載入 report JSON",
            BackTooltip = "返回",
            ModeLabel = "模式",
            TargetsLabel = "目標",
            ReviewReplacementInputsTooltip = "查看已選擇的 replacement inputs",
            InputFilesTitle = "輸入檔案",
            OutputLayoutTitle = "輸出配置",
            PlanTitle = "計畫",
            ValidationTitle = "驗證",
            GeneralReplaceMappingTitle = "General replace mapping",
            GeneralMergeMappingTitle = "General merge mapping",
            ExplicitMappingsTitle = "明確 mappings",
            AddRangeLabel = "+ 新增範圍",
            AddMappingLabel = "+ 新增 mapping",
            StartLabel = "起始",
            EndLabel = "結束",
            SourceStartLabel = "來源起始",
            TargetStartLabel = "目標起始",
            LengthLabel = "長度",
            SourceBinLabel = "Source BIN",
            ReplacementBinLabel = "Replacement BIN",
            OutputLengthLabel = "輸出長度",
            OutputLengthPlaceholder = "0x...",
            BrowseLabel = "瀏覽",
            RequiredLabel = "必填",
            OptionalLabel = "選填",
            NoBinSelectedLabel = "尚未選擇 BIN",
            MergeDpSlotDescription = "Standard Merge 的 Display payload",
            MergeTpSlotDescription = "Standard Merge 的 Touch payload",
            MergeLdSlotDescription = "只有選定 profile 使用 LD 時才需要",
            BaseFlashBinTitle = "Base flash BIN",
            BaseFlashBinDescription = "取代前的參考韌體映像",
            DpReplacementBinTitle = "DP replacement BIN",
            DpReplacementBinDescription = "DP replacement 會依 base BIN 長度處理；原 TP 範圍會從 base 還原。",
            TpReplacementBinTitle = "TP replacement BIN",
            TpReplacementBinDescription = "核准 touch/CRC refresh 流程使用的 TP replacement input。",
            LdReplacementBinTitle = "LD replacement BIN",
            LdReplacementBinDescription = "只有 DP Replace profile 顯示 LD 時才使用的選填 payload。",
            CtrlRamReplacementBinDescription = "CtrlRAM region replacement；未選擇的 slot 保留 base 內容。",
            SelectReplacementBinTooltip = "選擇 replacement BIN",
            SelectSourceBinTooltip = "選擇 source BIN",
            RemoveRangeTooltip = "移除範圍",
            RemoveMappingTooltip = "移除 mapping",
            GeneralReplaceRuleBaseTitle = "Base image",
            GeneralReplaceRuleBaseDetail = "未 mapping 的 bytes 會保留選定 base BIN 的內容。",
            GeneralReplaceRuleBoundsTitle = "目標邊界",
            GeneralReplaceRuleBoundsDetail = "範圍必須落在 base image 內並避開 protected regions。",
            GeneralReplaceRuleLengthTitle = "輸入長度",
            GeneralReplaceRuleLengthDetail = "Replacement BIN data 必須覆蓋 mapping 範圍長度。",
            GeneralReplaceValidationDetail = "執行時會使用已編譯的 explicit mappings；TP 範圍需要核准的 Combiner CRC/header refresh。",
            GeneralReplaceMappingsDetail = "每列將一個 inclusive target range 對應到一個 replacement BIN。",
            GeneralMergeMappingDetail = "將明確 source BIN ranges 複製到 blank output image；不執行 postbuild command。",
            GeneralMergeMappingsDetail = "每列將一個 source BIN range 複製到一個 output target range。",
            CtrlRamInputFilesDetail = "只放入要更動的 CtrlRAM 區域檔案；未放入的區域保留 base firmware。",
            AbCodeMergeTitle = "AB Code Merge",
            AbCodeMergeDetail = "保留到 dedicated AB Code profile 與 TP CRC/start-address 行為核准後再啟用。",
            SettingsCatalogTitle = "Catalog",
            SettingsCatalogSubtitle = "Application catalog 提供的 profile 與 flash-map 狀態。",
            SettingsRuntimeChecksTitle = "執行檢查",
            SettingsRuntimeChecksSubtitle = "打包好的 validation 與 header refresh readiness。",
            SettingsDiagnosticsTitle = "診斷",
            SettingsDiagnosticsSubtitle = "Report review 與不執行韌體的診斷存取。",
            SettingsPreferencesTitle = "偏好設定",
            SettingsPreferencesSubtitle = "本機 shell 偏好會儲存並在啟動時還原。",
            ThemeLabel = "主題",
            StrictnessLabel = "審查嚴格度",
            LanguageLabel = "語言",
            SettingsInspectorKicker = "檢視",
            SettingsReadinessTitle = "設定狀態",
            ReportToastTitle = "Report",
            ReplaceSelectionTitle = "Replace selection",
            CloseSelectionTooltip = "關閉 selection overview",
            SelectedReplacementsTitle = "已選 replacements",
            RequiredBeforeBuildTitle = "Build 前必填",
            CloseLabel = "關閉",
            SaveReportLabel = "儲存 report",
            CloseReportTooltip = "關閉 report",
            ReportHistoryTitle = "Report history",
            BackToReportLabel = "回到 report",
            ClearAllLabel = "全部清除",
            ClearHistoryLabel = "清除 history",
            ClearHistoryTooltip = "清除全部 report history (Ctrl+Shift+Delete)",
            NoReportHistoryLabel = "目前沒有 report history。",
            RunLabel = "執行",
            OutputLabel = "輸出",
            RunResultReportReadyLabel = "report 已就緒",
            ChangeReviewTitle = "差異審查",
            EvidenceTitle = "審查明細",
            TraceLabel = "trace",
            OpenReportHistoryTooltip = "開啟 report history (Ctrl+H)",
            OpenReportHistoryAutomationName = "開啟 report history",
            ReportTabInputs = "輸入",
            ReportTabChanges = "差異",
            ReportTabOperations = "操作",
            ReportTabPostbuild = "Postbuild",
            ReportTabIssues = "問題",
            ReportTabRaw = "原始資料",
            RunMetadataTitle = "執行資訊",
            ReportFileLabel = "Report 檔案",
            StatusLabel = "狀態",
            ArtifactPathLabel = "Artifact path",
            InputsAndHashesTitle = "輸入檔案",
            EmptyInputsMessage = "此 report 沒有記錄 input artifact rows。",
            EmptyByteChangesMessage = "此 report 沒有記錄 output differences 或 changed ranges。",
            OutputChangesTitle = "輸出差異",
            DiffLabel = "Diff",
            RangeLabel = "範圍",
            ResultLabel = "結果",
            DetailLabel = "細節",
            ExplanationLabel = "說明",
            ReasonLabel = "原因",
            ChangedRangesTitle = "Changed ranges",
            EmptyOperationsMessage = "此 report 沒有記錄 copy/process operation steps。",
            OperationStepsTitle = "Operation steps",
            StepLabel = "Step",
            KindLabel = "Kind",
            SourceLabel = "Source",
            TargetLabel = "Target",
            ProcessorLabel = "Processor",
            EmptyPostbuildMessage = "此 report 沒有記錄 external postbuild/header refresh command。",
            HeaderRefreshTraceTitle = "Header refresh trace",
            EmptyIssuesMessage = "此 report 沒有記錄 issues 或 warnings。",
            IssuesAndWarningsTitle = "問題與警告",
            RangeTableTitle = "Range table",
            AddressSpaceLabel = "Address space",
            CommandArgvLabel = "Command argv",
            DeleteReportTooltip = "刪除此 report",
            MergeModeTooltip = "選擇 Standard、保留的 AB Code 或高自由度 General Merge。",
        };
    }
}

#pragma warning restore CS1591
