// Resource bags intentionally expose many concise bindable labels; XML comments on each label add noise.
#pragma warning disable CS1591

namespace NvtFwCombiner.Presentation.Avalonia.ViewModels;

internal sealed partial class ShellTextResources
{
    private static ShellTextResources CreateLocalized(ShellLanguage language)
    {
        T Pick<T>(T english, T traditionalChinese)
        {
            return language == ShellLanguage.ChineseTraditional ? traditionalChinese : english;
        }

        return new ShellTextResources
        {
            Language = language,
            HomeLabel = Pick("Home", "首頁"),
            CatalogLoadingTitle = Pick("Preparing capabilities", "正在準備功能"),
            CatalogLoadingDetail = Pick(
                "Loading the canonical catalog used by Merge and Replace.",
                "正在載入 Merge 與 Replace 共用的 canonical catalog。"),
            CatalogMaterializingDetail = Pick(
                "Preparing the canonical capability routes.",
                "正在準備 canonical capability routes。"),
            CatalogApplyingDetail = Pick(
                "Applying the validated capability state.",
                "正在套用已驗證的功能狀態。"),
            CatalogReadyDetail = Pick(
                "Capability state is ready.",
                "功能狀態已準備完成。"),
            CatalogLoadingFailedTitle = Pick("Capabilities unavailable", "功能目前無法使用"),
            CatalogLoadingFailedDetail = Pick(
                "The canonical catalog could not be loaded. Retry to restore Merge and Replace.",
                "無法載入 canonical catalog；請重試以恢復 Merge 與 Replace。"),
            RetryLabel = Pick("Retry", "重試"),
            CancelStartupLabel = Pick("Cancel startup", "取消啟動"),
            PreloadStatusTitle = Pick("Startup preparation", "啟動準備"),
            PreloadHistoryTitle = Pick("Report history", "報告記錄"),
            PreloadReportTitle = Pick("Startup report", "啟動報告"),
            PreloadExternalEnvironmentTitle = Pick("External tools", "外部工具"),
            PreloadViewsTitle = Pick("Preparing views", "正在準備畫面"),
            PreloadPendingDetail = Pick("Waiting to start", "等待開始"),
            PreloadBlockedDetail = Pick("Waiting for a required predecessor", "等待必要的前置工作"),
            PreloadRunningDetail = Pick("In progress", "進行中"),
            PreloadSucceededDetail = Pick("Complete", "已完成"),
            PreloadFailedDetail = Pick("Needs attention", "需要處理"),
            PreloadSkippedDetail = Pick("Skipped", "已略過"),
            PreloadCancelledDetail = Pick("Cancelled", "已取消"),
            SkipPreloadLabel = Pick("Skip", "略過"),
            CancelPreloadLabel = Pick("Cancel remaining", "取消剩餘工作"),
            MessageCenterTitle = Pick("Message Center", "訊息中心"),
            MessageCenterTooltip = Pick("Open reports and current system diagnostics", "開啟報告與目前系統診斷"),
            RunReportsLabel = Pick("Run reports", "執行報告"),
            SystemInformationLabel = Pick("System information", "系統資訊"),
            RefreshDiagnosticsLabel = Pick("Refresh", "重新整理"),
            ExportDiagnosticsLabel = Pick("Export diagnostics", "匯出診斷"),
            NoActiveDiagnosticsLabel = Pick("No active system diagnostics.", "目前沒有系統診斷問題。"),
            ActiveDiagnosticsLabel = Pick("Active diagnostics", "目前診斷"),
            ApplicationVersionLabel = Pick("Application", "應用程式"),
            RuntimeLabel = Pick("Runtime", "執行環境"),
            CatalogLabel = Pick("Catalog", "目錄"),
            ExternalToolsLabel = Pick("External tools", "外部工具"),
            OpenReportHistoryLabel = Pick("Open report history", "開啟報告記錄"),
            DiagnosticsExportedLabel = Pick("Diagnostics exported.", "診斷已匯出。"),
            DiagnosticsExportFailedLabel = Pick("Diagnostics could not be exported.", "無法匯出診斷。"),
            RefreshingDiagnosticsLabel = Pick("Refreshing system diagnostics.", "正在重新整理系統診斷。"),
            SystemActivityTitle = Pick("System activity", "系統活動"),
            SystemActivitySubtitle = Pick(
                "Important events and optional detailed actions from this app session.",
                "本次應用程式工作階段的重要事件與可選詳細操作。"),
            ImportantActivityLabel = Pick("Important", "重要"),
            WarningActivityLabel = Pick("Warnings", "警告"),
            ErrorActivityLabel = Pick("Errors", "錯誤"),
            ShowDebugActivityLabel = Pick("Show Debug activity", "顯示 Debug 活動"),
            HideDebugActivityLabel = Pick("Hide Debug activity", "隱藏 Debug 活動"),
            SessionActivityNotice = Pick(
                "Debug adds user actions and internal state changes. Activity is cleared when the app closes.",
                "Debug 會加入使用者操作與內部狀態變更；關閉應用程式後會清除活動紀錄。"),
            NoActivityLabel = Pick("No activity matches this filter.", "沒有符合目前篩選條件的活動。"),
            ExportActivityLabel = Pick("Export", "匯出"),
            WorkspaceTitle = Pick("Merge / Replace workspace", "合併 / 取代工作區"),
            WorkspaceSummary = Pick("Production-backed shell with built-in profiles, flash-map catalog, and report review.", "使用內建 profile、flash-map catalog 與 report review 的生產導向介面。"),
            PreviewActionLabel = Pick("Preview", "預覽"),
            BuildActionLabel = Pick("Build", "建立"),
            PreviewRunProgressAccessibleLabel = Pick("Preview in progress", "正在預覽"),
            BuildRunProgressAccessibleLabel = Pick("Build in progress", "正在建立"),
            ReportModalActionLabel = "Report",
            OutputDeliveryTitle = Pick("Build settings", "Build 設定"),
            OutputDeliverySummary = Pick(
                "Review the output, then confirm optional changes.",
                "檢查輸出內容，再確認需要的選項。"),
            OutputDeliveryBundleLabel = Pick(
                "Bundle output and sources",
                "將輸出與來源封裝成資料夾"),
            OutputDeliverySectionLabel = Pick("Delivery", "交付方式"),
            OutputDeliveryAdditionalLabel = Pick(
                "Also export A FlashCode as a loose BIN",
                "另外輸出 A FlashCode loose BIN"),
            OutputDeliveryAdditionalInBundleLabel = Pick(
                "Include A FlashCode in the bundle",
                "在 bundle 中包含 A FlashCode"),
            OutputDeliveryOutputLabel = Pick("Output", "輸出"),
            OutputDeliveryEditOutputNameLabel = Pick("Edit output filename", "編輯輸出檔名"),
            OutputDeliverySourcesLabel = Pick("Sources", "來源"),
            OutputDeliverySourcesSummaryFormat = Pick("{0} verified sources", "{0} 個已驗證來源"),
            OutputDeliveryFolderNameLabel = Pick("Bundle folder name", "Bundle 資料夾名稱"),
            OutputDeliveryParentLabel = Pick("Parent folder", "上層資料夾"),
            OutputDeliveryChooseParentLabel = Pick("Choose folder", "選擇資料夾"),
            OutputDeliveryEditBundleDestinationLabel = Pick("Edit bundle directory", "編輯 Bundle 目錄"),
            OutputDeliveryDoneEditingLabel = Pick("Done", "完成"),
            OutputDeliveryConfirmLabel = Pick("Continue", "繼續"),
            OutputDeliveryCancelLabel = Pick("Cancel", "取消"),
            OutputDeliveryReadySummary = Pick("Ready to continue", "已可繼續"),
            OutputDeliveryDestinationRequired = Pick(
                "Choose a parent folder and enter a valid bundle folder name.",
                "請選擇上層資料夾並輸入有效的 bundle 資料夾名稱。"),
            OutputDeliveryStaleAcceptedSession = Pick(
                "The accepted inputs changed. Close this confirmation and build again.",
                "已接受的輸入已變更。請關閉此確認視窗後重新 Build。"),
            DeviceContextTitle = Pick("Device context", "裝置條件"),
            IcLabel = "IC",
            NumberLabel = Pick("Number", "數量"),
            DeviceContextStatus = Pick("refresh profile, slots, validation", "刷新 profile、slot、validation"),
            SettingsPreview = Pick(
                new PlanningCardText(
                    "Settings",
                    "Review installed capabilities and working preferences.",
                    [
                        "Version and supported IC count",
                        "Executable profile and tool coverage",
                        "Theme and language preference",
                    ],
                    "Implemented settings only"),
                new PlanningCardText(
                    "設定",
                    "查看已安裝功能與實際生效的偏好設定。",
                    [
                        "版本與支援 IC 數量",
                        "可執行 profile 與 tool coverage",
                        "主題與語言偏好",
                    ],
                    "只保留已實作設定")),
            MergePreview = Pick(
                new PlanningCardText(
                    "Merge",
                    "Standard, AB Code, and Customized workflows.",
                    [
                        "Profile: built-in Standard Merge",
                        "Slots: DP, TP, optional LDC",
                        "950/951 DP Perspective policy",
                    ],
                    "Build wired"),
                new PlanningCardText(
                    "合併",
                    "Standard、AB Code 與 Customized 流程。",
                    [
                        "Profile：內建 Standard Merge",
                        "Slots：DP、TP、選用 LDC",
                        "950/951 DP Perspective policy",
                    ],
                    "Build 已串接")),
            ReplacePreview = Pick(
                new PlanningCardText(
                    "Replace",
                    "DP, CtrlRAM, and Customized policies.",
                    [
                        "Device context: shared IC and Number",
                        "DP Replace includes separate DP and LDC payloads",
                        "CtrlRAM Replace uses approved CtrlRAM regions",
                        "CRC/header: combiner.exe postbuild core",
                    ],
                    "Build wired; CtrlRAM postbuild enabled"),
                new PlanningCardText(
                    "取代",
                    "DP、CtrlRAM 與 Customized policy。",
                    [
                        "裝置條件：共用 IC 與數量",
                        "DP Replace 包含分開的 DP 與 LDC payload",
                        "CtrlRAM Replace 使用核准的 CtrlRAM regions",
                        "CRC/header：combiner.exe postbuild core",
                    ],
                    "Build 已串接；CtrlRAM postbuild 已啟用")),
            InitialRunTitle = Pick("No run yet", "尚未執行"),
            InitialRunDetail = Pick("Drop required BIN files, then run Build.", "放入必要 BIN 檔後即可建立。"),
            NoOutputLabel = Pick("No output", "無輸出"),
            WaitingForRequiredInputsLabel = Pick("Waiting for required inputs", "等待必要輸入"),
            WorkflowKicker = Pick("WORKFLOW", "流程"),
            NavigationClearTitle = Pick("Clear selected files and leave this page?", "清除已選檔案並離開此頁？"),
            NavigationClearDetail = Pick(
                "Continuing clears the BIN and mapping-file selections on this page. IC, Number, Mode, mapping addresses, and Settings preferences are kept.",
                "繼續後會清除此頁的 BIN 與 mapping 檔案選取；IC、Number、Mode、mapping 位址及 Settings 偏好仍會保留。"),
            NavigationClearConfirmLabel = Pick("Clear and continue", "清除並繼續"),
            NavigationClearCancelLabel = Pick("Stay on this page", "留在此頁"),
            OpenLabel = Pick("Open", "開啟"),
            PendingLabel = Pick("Pending", "待實作"),
            LoadJsonLabel = Pick("Load Report", "載入報告"),
            LoadJsonTooltip = Pick("Load a report", "載入報告"),
            BackTooltip = Pick("Back", "返回"),
            ModeLabel = Pick("Mode", "模式"),
            TargetsLabel = Pick("Targets", "目標"),
            ReviewReplacementInputsTooltip = Pick("Review selected replacement inputs", "查看已選擇的 replacement inputs"),
            InputFilesTitle = Pick("Input files", "輸入檔案"),
            OutputLayoutTitle = Pick("Output layout", "輸出配置"),
            OutputLayoutChangedStateLabel = Pick("Changed", "已變更"),
            OutputLayoutKeptStateLabel = Pick("Kept", "保留"),
            PlanTitle = Pick("Plan", "計畫"),
            ValidationTitle = Pick("Validation", "驗證"),
            GeneralReplaceMappingTitle = "Customized Replace mapping",
            GeneralMergeMappingTitle = "Customized Merge mapping",
            ExplicitMappingsTitle = Pick("Explicit mappings", "明確 mappings"),
            AddRangeLabel = Pick("+ Add range", "+ 新增範圍"),
            AddMappingLabel = Pick("+ Add mapping", "+ 新增 mapping"),
            StartLabel = Pick("Start", "起始"),
            EndLabel = Pick("End", "結束"),
            SourceStartLabel = Pick("Source start", "來源起始"),
            TargetStartLabel = Pick("Target start", "目標起始"),
            LengthLabel = Pick("Length", "長度"),
            SourceBinLabel = "Source BIN",
            ReplacementBinLabel = "Replacement BIN",
            OutputLengthLabel = Pick("Output length", "輸出長度"),
            OutputLengthPlaceholder = "0x...",
            OutputFillByteLabel = Pick("Fill byte", "填充值元組"),
            OutputFillBytePlaceholder = "0x00",
            BrowseLabel = Pick("Browse", "瀏覽"),
            ClearFirmwareSelectionLabel = Pick("Clear selected file", "清除已選檔案"),
            RequiredLabel = Pick("Required", "必填"),
            OptionalLabel = Pick("Optional", "選填"),
            NoBinSelectedLabel = Pick("No BIN selected", "尚未選擇 BIN"),
            FirmwareSlotCheckingLabel = Pick("Checking", "檢查中"),
            FirmwareSlotVerifiedLabel = Pick("Verified", "已驗證"),
            CtrlRamBaseInspectedLabel = Pick("Base inspected", "基礎檔已檢查"),
            CtrlRamBaseInspectedDetail = Pick(
                "Base firmware was inspected; select at least one CtrlRAM replacement to compile the exact operation.",
                "已檢查基礎韌體；請至少選擇一個 CtrlRAM 取代檔，才能編譯確切操作。"),
            FirmwareSlotWarningLabel = Pick("Warning", "警告"),
            FirmwareSlotErrorLabel = Pick("Error", "錯誤"),
            FirmwareSlotNotApplicableLabel = Pick("Not applicable", "不適用"),
            FirmwareSlotUnknownValueLabel = Pick("Unknown", "未知"),
            FirmwareSlotUnknownFactDetail = Pick(
                "Metadata could not be decoded; review the selected file and report details.",
                "無法解碼 metadata；請檢查選定檔案與 report 詳細資料。"),
            FirmwareSlotPendingFactDetail = Pick(
                "Load the prerequisite input, then inspect again.",
                "請載入必要的前置輸入後重新檢查。"),
            FirmwareSlotWarningFactDetail = Pick(
                "This metadata value requires review; inspect the selected file and report details.",
                "此 metadata 值需要確認；請檢查選定檔案與 report 詳細資料。"),
            FirmwareSlotErrorFactDetail = Pick(
                "This metadata value blocks the workflow; resolve the reported issue.",
                "此 metadata 值會阻擋流程；請解決 report 中的問題。"),
            FirmwareSlotShowMoreFactsTemplate = Pick("Show {0} more details", "顯示另外 {0} 項詳細資料"),
            FirmwareSlotShowFewerFactsLabel = Pick("Show fewer details", "收合詳細資料"),
            MergeDpSlotDescription = Pick("Display payload for Standard Merge", "Standard Merge 的 Display payload"),
            MergeTpSlotDescription = Pick("Touch payload for Standard Merge", "Standard Merge 的 Touch payload"),
            MergeLdcSlotDescription = Pick("Optional LDC input when the selected profile exposes an LDC region", "選定 profile 包含 LDC 區域時可選擇 LDC 輸入"),
            DpReplacementBinTitle = Pick("DP replacement BIN", "DP 取代 BIN 檔案"),
            SelectReplacementBinTooltip = Pick("Select replacement BIN", "選擇 replacement BIN"),
            SelectSourceBinTooltip = Pick("Select source BIN", "選擇 source BIN"),
            RemoveRangeTooltip = Pick("Remove range", "移除範圍"),
            RemoveMappingTooltip = Pick("Remove mapping", "移除 mapping"),
            GeneralReplaceRuleBaseTitle = "Base image",
            GeneralReplaceRuleBaseDetail = Pick("Unmapped bytes stay from the selected base BIN.", "未 mapping 的 bytes 會保留選定 base BIN 的內容。"),
            GeneralReplaceRuleBoundsTitle = Pick("Target bounds", "目標邊界"),
            GeneralReplaceRuleBoundsDetail = Pick("Ranges must fit the base image and avoid protected regions.", "範圍必須落在 base image 內並避開 protected regions。"),
            GeneralReplaceRuleLengthTitle = Pick("Input length", "輸入長度"),
            GeneralReplaceRuleLengthDetail = Pick("Replacement BIN data must cover the mapped range length.", "Replacement BIN data 必須覆蓋 mapping 範圍長度。"),
            GeneralReplaceValidationDetail = Pick("Validated execution uses compiled explicit mappings; TP ranges require approved Combiner CRC/header refresh.", "執行時會使用已編譯的 explicit mappings；TP 範圍需要核准的 Combiner CRC/header refresh。"),
            GeneralReplaceMappingsDetail = Pick("Each row maps Start + Length to a BIN, Hex Overwrite, or Hex Fill source.", "每列以 Start + Length 對應 BIN、Hex Overwrite 或 Hex Fill 來源。"),
            GeneralSourceKindLabel = Pick("Source", "來源"),
            GeneralSourceValueLabel = Pick("Value / BIN", "數值 / BIN"),
            GeneralFileSourceLabel = Pick("File", "檔案"),
            GeneralHexOverwriteSourceLabel = "Hex Overwrite",
            GeneralHexFillSourceLabel = "Hex Fill",
            GeneralInlineHexPlaceholder = Pick("hex bytes", "十六進位 bytes"),
            GeneralInlineHexGuidance = Pick("Enter hexadecimal value", "輸入十六進位數值"),
            HexEditorSaveAsLabel = Pick("Save as...", "另存新檔..."),
            HexEditorSaveConfirmationTitle = Pick("Save new BIN?", "儲存新的 BIN？"),
            HexEditorSaveConfirmationDetail = Pick("Edits remain in memory until export. Save As writes a new BIN only; it never changes the opened source BIN and does not run firmware validation or postbuild.", "修改只保留在記憶體直到輸出。另存新檔只會寫出新的 BIN，絕不改寫已開啟來源，且不會執行韌體驗證或 postbuild。"),
            HexEditorSaveConfirmationActionLabel = Pick("Choose output", "選擇輸出位置"),
            GeneralMergeMappingDetail = Pick("Copy explicit source BIN ranges into a blank output image. No postbuild command runs.", "將明確 source BIN ranges 複製到 blank output image；不執行 postbuild command。"),
            GeneralMergeMappingsDetail = Pick("Each row copies one source BIN range to one output target range.", "每列將一個 source BIN range 複製到一個 output target range。"),
            CtrlRamInputFilesDetail = Pick("Use a complete FlashCode or TP FW as Reference firmware. Add only the CtrlRAM areas to replace; short files stop at EOF and bytes beyond each maximum are ignored.", "Reference firmware 可使用完整 FlashCode 或 TP FW。只加入要取代的 CtrlRAM 區域；短檔於 EOF 停止，超過各區上限的 bytes 會忽略。"),
            CtrlRamFirmwareVersionTitle = Pick("TP version", "TP 版本"),
            CtrlRamFirmwareVersionDetail = Pick("Choose the source, then enter the version.", "選擇版本來源，再輸入版本。"),
            CtrlRamFirmwareVersionKeepLabel = Pick("Keep base", "沿用 Base"),
            CtrlRamFirmwareVersionEditLabel = Pick("Set new", "設定新版本"),
            CtrlRamFirmwareVersionCurrentLabel = Pick("Base firmware TP version", "Base firmware 的 TP 版本"),
            CtrlRamFirmwareVersionByteLabel = Pick("FW version", "FW 版本"),
            CtrlRamFirmwareSubVersionByteLabel = Pick("FW sub-version", "FW 子版本"),
            CtrlRamFirmwareVersionSourceDetail = Pick("Read from the verified NVT Backup in the base firmware. Postbuild propagates the chosen value to the output Backup.", "此值取自 base firmware 內已驗證的 NVT Backup；postbuild 會把選定版本帶到輸出 Backup。"),
            CtrlRamFirmwareVersionEditUnavailableDetail = Pick("The NVT Backup version metadata is unavailable or invalid, so only keeping the original version is allowed.", "NVT Backup 的版本資訊不存在或驗證失敗，因此只能維持原本版本。"),
            CtrlRamFirmwareVersionInvalidByteDetail = Pick("Enter each version field as one hexadecimal byte from 00 to FF.", "每個版本欄位須輸入 00 到 FF 的一個十六進位 byte。"),
            CtrlRamFirmwareVersionChooseOutputLabel = Pick("Continue to output", "繼續選擇輸出"),
            AbCodeMergeTitle = "AB Code Merge",
            InitialCodeAndLdcSlotHint = Pick("(Initial Code + LDC)", "（Initial Code + LDC）"),
            AbCodeMergeDetail = Pick(
                "Compose one compiled DP_AB container with independent TPA and TPB payloads. Input versions are informational and never choose the route.",
                "以 compiled profile 合成一個 DP_AB container 與獨立 TPA、TPB payload；input 版本只供確認，絕不選擇執行路徑。"),
            AbSameTpOptionLabel = Pick("Use the same TP for A and B", "A 與 B 使用相同 TP"),
            AbSameTpLinkedLabel = Pick("Same as TPA", "與 TPA 相同"),
            AbSameTpConflictTitle = Pick("Choose the shared TP", "選擇共用 TP"),
            AbSameTpConflictDetail = Pick(
                "TPA and TPB currently use different files. Choose which one will supply both logical slots, or cancel without changing either selection.",
                "TPA 與 TPB 目前使用不同檔案。請選擇要讓哪一個檔案供應兩個 logical slot，或取消並保留兩個現有選擇。"),
            AbSameTpKeepALabel = Pick("Keep TPA", "保留 TPA"),
            AbSameTpKeepBLabel = Pick("Keep TPB", "保留 TPB"),
            IcDetailTitle = Pick("IC details", "IC 詳細資訊"),
            IcDetailFamilyLabel = Pick("Family", "Family"),
            IcDetailReuseLabel = Pick("Reusable scope", "可沿用範圍"),
            IcDetailRuntimeLabel = Pick("Runtime", "可執行流程"),
            IcDetailEvidenceLabel = Pick("Evidence", "Evidence"),
            IcDetailSupportLabel = Pick("Support", "支援說明"),
            SettingsOverviewNavigationLabel = Pick("General", "一般"),
            SettingsPreferencesNavigationLabel = Pick("Appearance", "外觀"),
            SettingsOverviewTitle = Pick("Product information", "產品資訊"),
            SettingsOverviewSubtitle = Pick(
                "Installed version and authoring availability from the current catalog.",
                "已安裝版本，以及目前目錄中的編輯可用性。"),
            SettingsCapabilitiesTitle = Pick("Implemented capabilities", "已實作功能"),
            SettingsCapabilitiesSubtitle = Pick("Authoring availability with separate execution and verification details.", "編輯可用性，以及分開呈現的執行與驗證資訊。"),
            SettingsPreferencesTitle = Pick("Preferences", "偏好設定"),
            SettingsPreferencesSubtitle = Pick("Preferences that take effect now and are restored on startup.", "立即生效並在啟動時還原的本機偏好。"),
            ThemeLabel = Pick("Theme", "主題"),
            LanguageLabel = Pick("Language", "語言"),
            SystemThemeChoiceLabel = Pick("System", "跟隨系統"),
            LightThemeChoiceLabel = Pick("Light", "淺色"),
            DarkThemeChoiceLabel = Pick("Dark", "深色"),
            EnglishLanguageChoiceLabel = Pick("English", "英文"),
            ChineseTraditionalLanguageChoiceLabel = Pick("Traditional Chinese", "繁體中文"),
            ReducedMotionLabel = Pick("Reduced motion", "減少動態效果"),
            ReducedMotionDescription = Pick(
                "Keep step status visible while removing non-essential progress animation.",
                "保留步驟狀態，同時停用非必要的進度動畫。"),
            SupportMatrixTitle = Pick("Support Matrix", "支援矩陣"),
            SupportMatrixSubtitle = Pick(
                "See which workflows are defined for each IC and how strongly each route is verified. Focus a cell for exact details.",
                "查看每個 IC 已定義的工作流程與路徑驗證程度；聚焦任一格可查看完整明細。"),
            SupportMatrixIcLabel = "IC",
            SupportMatrixIcCountLabel = Pick("IC Count", "IC 數量"),
            SupportMatrixMapVariantLabel = Pick("Map variant", "映射變體"),
            SupportMatrixAuthoringLabel = Pick("Authoring", "編輯"),
            SupportMatrixExecutionLabel = Pick("Execution", "執行"),
            SupportMatrixPublicationLabel = Pick("Publication", "發布"),
            SupportMatrixEvidenceLabel = Pick("Evidence", "證據"),
            SupportMatrixBlockerLabel = Pick("Blocker", "阻擋原因"),
            SupportMatrixCatalogVersionLabel = Pick("Catalog version:", "目錄版本："),
            SupportMatrixSourceHashLabel = Pick("Source SHA-256:", "來源 SHA-256："),
            SupportMatrixResolutionTokenLabel = Pick("Publication token:", "發布識別碼："),
            SupportMatrixFingerprintLabel = Pick("Capability fingerprint", "能力指紋"),
            SupportMatrixNoBlockerLabel = Pick("Clear", "無阻擋"),
            SupportMatrixLegendTitle = Pick("Verification status", "驗證狀態"),
            SupportMatrixReviewedEvidenceLabel = Pick("Verified", "已驗證"),
            SupportMatrixContractOnlyLabel = Pick("Defined only", "僅有定義"),
            SupportMatrixReviewRequiredLabel = Pick("Needs review", "待審查"),
            SupportMatrixBlockedLabel = Pick("Blocked", "已阻擋"),
            SupportMatrixNotDeclaredLabel = Pick("Not declared", "未宣告"),
            SupportMatrixHoverHint = Pick(
                "Status summarizes verification evidence and any route blockers; focus a cell for details.",
                "狀態彙整驗證證據與路徑阻擋原因；聚焦任一格可查看明細。"),
            SupportMatrixLoadingTitle = Pick("Loading Support Matrix", "正在載入支援矩陣"),
            SupportMatrixLoadingDetail = Pick(
                "The first complete canonical catalog publication is still being prepared.",
                "第一份完整 canonical catalog publication 仍在準備中。"),
            SupportMatrixEmptyTitle = Pick("No capability routes", "沒有 capability 路徑"),
            SupportMatrixEmptyDetail = Pick(
                "The current catalog is coherent but does not publish any exact routes.",
                "目前 catalog 完整，但沒有發布任何 exact route。"),
            SupportMatrixColdStartTitle = Pick("Support Matrix unavailable", "支援矩陣無法使用"),
            SupportMatrixColdStartDetail = Pick(
                "No valid catalog snapshot exists. Resolve the catalog diagnostic before using Build.",
                "目前沒有有效的 catalog snapshot；請先處理 catalog diagnostic，再使用 Build。"),
            SupportMatrixLastKnownGoodTitle = Pick(
                "Showing last known good catalog",
                "顯示最後可用的 catalog"),
            SupportMatrixLastKnownGoodDetail = Pick(
                "Reload failed. The retained matrix is coherent but stale until a successful reload.",
                "Reload 失敗；保留的矩陣仍完整，但在成功 reload 前屬於過期資料。"),
            NotAvailableLabel = Pick("Not available", "無法取得"),
            ReportToastTitle = "Report",
            ReplaceSelectionTitle = "Replace selection",
            CloseSelectionTooltip = Pick("Close selection overview", "關閉 selection overview"),
            SelectedReplacementsTitle = Pick("Selected replacements", "已選 replacements"),
            RequiredBeforeBuildTitle = Pick("Required before Build", "Build 前必填"),
            CloseLabel = Pick("Close", "關閉"),
            SaveReportLabel = Pick("Save report", "儲存 report"),
            BuildCompletedTitle = Pick("Build complete", "Build 完成"),
            BuildCompletedDetail = Pick(
                "The output BIN is ready. You can close this message or show the file in Explorer.",
                "輸出 BIN 已經完成。你可以關閉此訊息，或在檔案總管中顯示檔案。"),
            BuildCompletedOutputLabel = Pick("Output BIN", "輸出 BIN"),
            BuildCompletedOpenFolderLabel = Pick("Show output BIN", "顯示輸出 BIN"),
            LatestOutputOpenFolderLabel = Pick(
                "Reveal and focus the latest output in File Explorer",
                "在檔案總管中顯示並選取最新輸出檔案"),
            LatestOutputActionLabel = Pick("View file", "檢視檔案"),
            BuildCompletedOkLabel = Pick("OK", "確定"),
            BuildCompletedOpenFolderError = Pick(
                "Explorer could not select the output BIN. It may have moved or been deleted.",
                "檔案總管無法選取輸出 BIN；檔案可能已被移動或刪除。"),
            AbAFlashCodePromptTitle = Pick("Also export A FlashCode?", "是否也輸出 A FlashCode？"),
            AbAFlashCodePromptDetail = Pick(
                "Choose both output names before Build. The A FlashCode is copied from the declared A range of the same completed AB image.",
                "Build 前會先選擇兩個輸出名稱；A FlashCode 會從同一次完成的 AB image 之已宣告 A 範圍複製。"),
            AbAFlashCodePromptYesLabel = Pick("Yes, export A Code", "是，也輸出 A Code"),
            AbAFlashCodePromptNoLabel = Pick("No, AB only", "否，只輸出 AB"),
            BuildCompletedAdditionalOutputLabel = Pick("A FlashCode", "A FlashCode"),
            FileRevealFailedTitle = Pick("File unavailable", "檔案無法開啟"),
            FileRevealFailedDetail = Pick(
                "Explorer could not select this BIN. It may have moved or been deleted.",
                "檔案總管無法選取此 BIN；檔案可能已被移動或刪除。"),
            CloseReportTooltip = Pick("Close report", "關閉 report"),
            ReportHistoryTitle = "Report history",
            BackToReportLabel = Pick("Back to report", "回到 report"),
            ClearAllLabel = Pick("Clear all", "全部清除"),
            ClearHistoryLabel = Pick("Clear history", "清除 history"),
            ClearHistoryTooltip = Pick("Clear all report history (Ctrl+Shift+Delete)", "清除全部 report history (Ctrl+Shift+Delete)"),
            NoReportHistoryLabel = Pick("No report history.", "目前沒有 report history。"),
            RunLabel = Pick("Run", "執行"),
            OutputLabel = Pick("Output", "輸出"),
            RunResultReportReadyLabel = Pick("report ready", "report 已就緒"),
            PrimaryReasonLabel = Pick("Primary reason", "主要原因"),
            FailedStepLabel = Pick("Failed step", "失敗步驟"),
            OutputImpactLabel = Pick("Output impact", "輸出影響"),
            NextActionLabel = Pick("Next action", "下一步"),
            ChangeReviewTitle = Pick("Change review", "差異審查"),
            EvidenceTitle = Pick("Audit details", "審查明細"),
            TraceLabel = "trace",
            OpenReportHistoryTooltip = Pick("Open report history (Ctrl+H)", "開啟 report history (Ctrl+H)"),
            OpenReportHistoryAutomationName = Pick("Open report history", "開啟 report history"),
            ReportTabInputs = Pick("Inputs", "輸入"),
            ReportTabChanges = Pick("Changes", "差異"),
            ReportTabOperations = Pick("Operations", "操作"),
            ReportTabPostbuild = "Postbuild",
            ReportTabIssues = Pick("Issues", "問題"),
            ReportTabRaw = Pick("Raw", "原始資料"),
            RawReportTitle = Pick("Raw report JSON", "原始 report JSON"),
            RawReportDetail = Pick("Audit-only source data. Use the other tabs for normal review.", "僅供稽核與除錯；一般檢視請使用其他分頁。"),
            RunMetadataTitle = Pick("Run metadata", "執行資訊"),
            ReportFileLabel = Pick("Report file", "Report 檔案"),
            FileLabel = Pick("File", "檔案"),
            SizeLabel = Pick("Size", "大小"),
            StateLabel = Pick("State", "狀態"),
            StatusLabel = Pick("Status", "狀態"),
            ArtifactPathLabel = "Artifact path",
            InputsAndHashesTitle = Pick("Input files", "輸入檔案"),
            EmptyInputsMessage = Pick("No input artifact rows were recorded in this report.", "此 report 沒有記錄 input artifact rows。"),
            EmptyByteChangesMessage = Pick("No output differences or changed ranges were recorded.", "此 report 沒有記錄 output differences 或 changed ranges。"),
            OutputChangesTitle = Pick("Output changes", "輸出差異"),
            HexDiffViewportTitle = Pick("Read-only Hex Diff", "唯讀 Hex Diff"),
            HexDiffShowOriginalRowsLabel = Pick("Show original rows for changes", "在變更列下方顯示原始內容"),
            HexDiffOriginalRowLabel = Pick("original", "原始"),
            HexDiffRangeScrollAutomationName = Pick("Scroll the selected changed range", "捲動所選變更區段"),
            HexDiffRangeNavigatorTitle = Pick("Changed ranges", "變更區段"),
            HexDiffRangeNavigatorDetail = Pick("Select a range to jump to its bytes. Review-required ranges appear first.", "選取區段即可跳到對應位元組；待審查區段優先顯示。"),
            HexDiffResizeAutomationName = Pick("Resize Hex Diff and changed ranges panels", "調整 Hex Diff 與變更區段面板寬度"),
            HexDiffSelectedRangeLabel = Pick("Viewing", "目前檢視"),
            HexDiffWhyLabel = Pick("Why", "原因"),
            BinInspectorTitle = Pick("BIN Inspector", "BIN 檢視器"),
            BinInspectorViewportTitle = Pick("Resolved structure bytes", "已解析結構位元組"),
            BinInspectorRangeScrollAutomationName = Pick("Scroll resolved structure bytes", "捲動已解析結構位元組"),
            BinInspectorResizeAutomationName = Pick("Resize BIN bytes and metadata panels", "調整 BIN 位元組與中繼資料面板寬度"),
            BinInspectorStructuresTitle = Pick("Structures", "結構"),
            BinInspectorFieldsTitle = Pick("Fields", "欄位"),
            BinInspectorNoFieldsLabel = Pick("No declared fields", "沒有已宣告欄位"),
            BinInspectorNoByteSelectedLabel = Pick("No BIN byte selected.", "尚未選取 BIN 位元組。"),
            BinInspectorNoFieldLabel = Pick("no selected field", "未選取欄位"),
            BinInspectorSelectedByteFormat = Pick(
                "Address {0}, value {1}, field {2}.",
                "位址 {0}，值 {1}，欄位 {2}。"),
            RangeLabel = Pick("Range", "範圍"),
            ResultLabel = Pick("Result", "結果"),
            DetailLabel = Pick("Detail", "細節"),
            ChangedRangesTitle = Pick("Mutation details", "異動明細"),
            EmptyOperationsMessage = Pick("No copy/process operation steps were recorded.", "此 report 沒有記錄 copy/process operation steps。"),
            OperationStepsTitle = "Operation steps",
            KindLabel = "Kind",
            SourceLabel = "Source",
            EmptyPostbuildMessage = Pick("No external postbuild/header refresh command was recorded.", "此 report 沒有記錄 external postbuild/header refresh command。"),
            HeaderRefreshTraceTitle = "Header refresh trace",
            EmptyIssuesMessage = Pick("No issues or warnings were recorded.", "此 report 沒有記錄 issues 或 warnings。"),
            NoActionRequiredTitle = Pick("No action required", "不需處理"),
            IssuesAndWarningsTitle = Pick("Issues and warnings", "問題與警告"),
            RangeTableTitle = "Range table",
            AddressSpaceLabel = "Address space",
            CopyCommandTooltip = Pick("Copy command evidence", "複製命令證據"),
            DeleteReportTooltip = Pick("Delete this report", "刪除此 report"),
            MergeModeTooltip = Pick("Select Standard, reserved AB Code, or Customized Merge.", "選擇 Standard、保留的 AB Code 或 Customized Merge。"),
            WorkflowContextReplaceDetail = Pick("Choose the IC and IC count before opening Replace. You can change them later from the shared context row.", "進入 Replace 前先選擇 IC 與 IC 數量；之後仍可從共用條件列調整。"),
            WorkflowContextMergeDetail = Pick("Choose the IC before opening Merge. IC count is not part of the Standard, AB Code, or Customized Merge authoring context.", "進入 Merge 前先選擇 IC；Standard、AB Code 與 Customized Merge 的 authoring context 不使用 IC 數量。"),
            WorkflowContextSafetyDetail = Pick("This only selects the catalog context. It does not inspect, modify, or write any firmware file.", "這只會選擇 catalog 條件，不會讀取、修改或寫入任何 firmware 檔案。"),
            FirmwareIcMismatchTitle = Pick("Selected BIN suggests another IC", "選擇的 BIN 顯示另一個 IC"),
            FirmwareIcMismatchDetail = Pick("A marker found in the file name or printable header text differs from the current catalog context. This is a prompt only; it does not validate the BIN or change it.", "檔名或可讀 header 文字中的 IC marker 與目前 catalog 條件不同。此提示不會驗證或修改 BIN，也不會自動變更 IC。"),
            FirmwareIcMismatchCurrentLabel = Pick("Current IC", "目前 IC"),
            FirmwareIcMismatchDetectedLabel = Pick("Detected marker", "偵測 marker"),
            FirmwareIcMismatchKeepLabel = Pick("Keep current IC", "維持目前 IC"),
            FirmwareIcMismatchUseDetectedLabel = Pick("Use detected IC", "使用偵測到的 IC"),
            FirmwareNumberMismatchTitle = Pick("Firmware IC Number differs", "韌體 IC Number 不一致"),
            FirmwareNumberMismatchDetail = Pick(
                "FWConfig reports a chip count that does not match the selected Number. Switch to the matching plan and review the CtrlRAM inputs before Build; Cancel keeps the current selection but does not bypass validation.",
                "FWConfig 回報的 IC 數量與目前 Number 不一致。請切換到相符的 plan，並在 Build 前重新確認 CtrlRAM 輸入；取消會保留目前選擇，但不會略過驗證。"),
            FirmwareNumberMismatchCurrentLabel = Pick("Selected Number", "目前 Number"),
            FirmwareNumberMismatchDetectedLabel = Pick("FWConfig detected", "FWConfig 偵測"),
            FirmwareNumberMismatchCancelLabel = Pick("Cancel", "取消"),
            FirmwareNumberMismatchSwitchLabel = Pick("Switch Number", "切換 Number"),
            ContextUpdatedToastTitle = Pick("Context updated", "條件已更新"),
            FileDropRejectedTitle = Pick("File not selected", "未選取檔案"),
            FileDropRejectedDetail = Pick(
                "Drop exactly one local file.",
                "請一次拖放一個本機檔案。"),
            FirmwareInspectionLoadingTitle = Pick("Inspecting selected files", "正在檢查所選檔案"),
            FirmwareInspectionFailedTitle = Pick("Inspection unavailable", "檢查目前無法完成"),
            FirmwareInspectionCancelLabel = Pick("Cancel inspection", "取消檢查"),
            FirmwareInspectionLoadingStatus = Pick(
                "Inspecting the selected BIN… Build will be ready when the latest file snapshot is verified.",
                "正在檢查所選 BIN… 最新檔案快照確認完成後即可 Build。"),
            FirmwareInspectionStaleFileStatus = Pick(
                "Error: the file changed during inspection. Select it again before Build.",
                "錯誤：檢查期間檔案已變更。請重新選取檔案後再 Build。"),
            UtilToolsLabel = Pick("UTIL", "工具"),
            UtilToolsHomeTitle = Pick("Tool", "工具"),
            UtilToolsHomeDetail = Pick("Inspect and edit raw BIN files.", "檢視與編輯原始 BIN。"),
            HexEditorContextInsertZeroBeforeLabel = Pick("Insert 00 before this byte", "在此 byte 前插入 00"),
            HexEditorContextInsertZeroAfterLabel = Pick("Insert 00 after this byte", "在此 byte 後插入 00"),
            HexEditorContextInsertBytesBeforeLabel = Pick("Insert N bytes before...", "在此 byte 前插入 N bytes..."),
            HexEditorContextInsertBytesAfterLabel = Pick("Insert N bytes after...", "在此 byte 後插入 N bytes..."),
            HexEditorContextDeleteByteLabel = Pick("Delete this byte (shift later bytes left)", "刪除此 byte（後續 byte 左移）"),
            HexEditorContextSetToZeroLabel = Pick("Set this byte to 00", "將此 byte 設為 00"),
            HexEditorContextSetToFfLabel = Pick("Set this byte to FF", "將此 byte 設為 FF"),
            HexEditorContextGoToBlockStartLabel = Pick("Go to block start", "跳至區塊開頭"),
            HexEditorContextGoToBlockEndLabel = Pick("Go to block end", "跳至區塊結尾"),
            HexEditorSourceReadyDetail = Pick("In memory: 0x{0:X} bytes | {1} edit(s)", "記憶體中：0x{0:X} bytes | {1} 筆修改"),
            HexEditorSourceEmptyDetail = Pick("Open a BIN to inspect and edit a private in-memory work copy.", "開啟 BIN 後即可在私有記憶體工作副本中檢視與修改。"),
            HexEditorSaveCompletedDetail = Pick("Saved a new BIN: {0}", "已儲存新的 BIN：{0}"),
            HexEditorFileOperationFailedDetail = Pick("The BIN operation could not be completed.", "無法完成 BIN 操作。"),
            HexEditorNothingToUndoDetail = Pick("There is no in-memory change to undo.", "沒有可復原的記憶體修改。"),
            HexEditorNothingToRedoDetail = Pick("There is no reverted change to redo.", "沒有可重做的修改。"),
            HexEditorTitle = "Hex Editor",
            HexEditorDetail = Pick("Raw BIN utility. Edit an in-memory work copy, then Save As a new BIN. No IC, profile, CRC, or postbuild rule is applied.", "純 BIN 工具。修改只存在記憶體工作副本，另存新檔才輸出；不套用 IC、profile、CRC 或 postbuild 規則。"),
            HexEditorGoToAddressLabel = Pick("Go to address", "跳至位址"),
            HexEditorAsciiSearchLabel = Pick("Find ASCII", "搜尋 ASCII"),
            HexEditorAsciiSearchPlaceholder = Pick("Find ASCII", "搜尋 ASCII"),
            HexEditorAsciiSearchNotFoundDetail = Pick("ASCII text was not found in the in-memory BIN.", "目前記憶體 BIN 中找不到 ASCII 文字。"),
            HexEditorInvalidAsciiSearchDetail = Pick("Enter printable ASCII text to search.", "請輸入可顯示的 ASCII 文字。"),
            HexEditorAsciiSearchFoundDetail = Pick("{0}Match {1}/{2} at {3}", "{0}第 {1}/{2} 筆：{3}"),
            HexEditorAsciiSearchIndexTemplate = "{0}/{1}",
            HexEditorAsciiSearchWrappedLabel = Pick("Wrapped. ", "已從開頭繼續搜尋。"),
            HexEditorChangeTitle = Pick("Edit region", "編輯區段"),
            HexEditorChangedBlocksLabel = Pick("Edited blocks", "已修改區塊"),
            HexEditorNoChangedBlocksDetail = Pick("Applied changes will appear here for quick navigation.", "套用修改後會列在這裡，方便快速跳轉。"),
            HexEditorChangedBlockSelectedDetail = Pick("Edited block {0}/{1}: {2} to {3}", "修改區塊 {0}/{1}：{2} 至 {3}"),
            HexEditorSelectChangedBlockTooltip = Pick("Jump to the next contiguous edited block", "跳至下一個連續修改區塊"),
            HexEditorChangedBlockNavigationAccessibleTemplate = Pick(
                "Jump to the next edited block; {0} edited blocks",
                "跳至下一個修改區塊；共 {0} 個修改區塊"),
            HexEditorChangedBlockValueReasonSingleTemplate = Pick("Value changed at {0}: {1} -> {2}.", "{0} 的值由 {1} 變更為 {2}。"),
            HexEditorChangedBlockValueReasonMultipleTemplate = Pick("{0} values changed; first at {1}: {2} -> {3}.", "共 {0} 個值變更；第一筆位於 {1}：{2} -> {3}。"),
            HexEditorChangedBlockInsertReasonTemplate = Pick("Inserted {0} byte(s) at {1}; following addresses shifted right by {0}.", "在 {1} 插入 {0} bytes；後續位址向右偏移 {0}。"),
            HexEditorChangedBlockDeleteReasonTemplate = Pick("Deleted {0} byte(s) at {1}; following addresses shifted left by {0}.", "在 {1} 刪除 {0} bytes；後續位址向左偏移 {0}。"),
            HexEditorChangedBlockReasonFallback = Pick("The current memory bytes differ from the opened BIN in this range.", "此範圍的記憶體內容與開啟的 BIN 不同。"),
            HexEditorAddressColumnLabel = Pick("Address", "位址"),
            HexEditorAsciiColumnLabel = "ASCII",
            HexEditorDocumentScrollBarAutomationName = Pick("Hex document scroll bar", "Hex 文件捲軸"),
            HexEditorShowOriginalRowsLabel = Pick("Show original rows", "顯示原始列"),
            HexEditorHexBytesLabel = "Hex bytes",
            HexEditorWriteModeLabel = Pick("Write mode", "寫入模式"),
            HexEditorOverwriteModeLabel = Pick("Overwrite", "覆寫"),
            HexEditorFillModeLabel = Pick("Fill", "填滿"),
            HexEditorOverwriteModeTooltip = Pick("Write supplied bytes from Start. The sequence must end at or before End.", "由 Start 起依序覆寫輸入 bytes，最後一個 byte 不得超過 End。"),
            HexEditorFillModeTooltip = Pick("Repeat one entered byte across the entire selected range.", "將單一輸入 byte 重複寫滿整個所選範圍。"),
            HexEditorOverwriteGuidance = Pick("Writes supplied bytes from Start. They may be shorter than the selection, but never pass End.", "由 Start 起依序覆寫輸入的 bytes；可少於選取範圍，但不得超過 End。"),
            HexEditorFillGuidance = Pick("Repeats one byte across every address from Start through End.", "以單一 byte 填滿 Start 至 End 的所有位址。"),
            HexEditorApplyChangeLabel = Pick("Apply change", "套用修改"),
            HexEditorHexBytesPlaceholder = Pick("A5 5A or FF", "A5 5A 或 FF"),
            HexEditorUndoLabel = Pick("Undo", "復原"),
            HexEditorRedoLabel = Pick("Redo", "重做"),
            HexEditorUndoTooltip = Pick("Undo the latest in-memory edit (Ctrl+Z).", "復原上一筆記憶體修改（Ctrl+Z）。"),
            HexEditorRedoTooltip = Pick("Redo the latest reverted edit (Ctrl+Y).", "重做上一筆已復原的修改（Ctrl+Y）。"),
            HexEditorSaveAsTooltip = Pick("Export the in-memory work copy as a new BIN.", "將記憶體工作副本輸出成新的 BIN。"),
            HexEditorEditByteLabel = Pick("Edit byte", "編輯 byte"),
            HexEditorInvalidAddressDetail = Pick("Enter an in-range hexadecimal address in 0xABCDEF format.", "請以 0xABCDEF 格式輸入有效且在範圍內的十六進位位址。"),
            HexEditorInvalidByteDetail = Pick("Enter exactly one hexadecimal byte, for example A5.", "請輸入一個十六進位 byte，例如 A5。"),
            HexEditorInvalidRangeDetail = Pick("Start and End must define an in-range inclusive selection.", "Start 與 End 必須形成 BIN 內有效的含頭含尾範圍。"),
            HexEditorInputExceedsRangeDetail = Pick("Too many bytes for this selection. Overwrite starts at Start and must end at or before End.", "輸入 bytes 太多：覆寫會從 Start 開始，最後一個 byte 不得超過 End。"),
            HexEditorInvalidByteCountDetail = Pick("Byte count must be within the supported insert limit.", "Byte 數量必須位於支援的插入上限內。"),
            HexEditorInsertBytesBeforeTitle = Pick("Insert bytes before", "在前方插入 bytes"),
            HexEditorInsertBytesAfterTitle = Pick("Insert bytes after", "在後方插入 bytes"),
            HexEditorInsertBytesDetail = Pick("Insert zero-filled bytes into the memory copy. Later addresses shift; the source BIN stays unchanged.", "將 0x00 bytes 插入記憶體副本；後續位址會偏移，來源 BIN 不會被修改。"),
            HexEditorInsertByteCountLabel = Pick("Byte count", "Byte 數量"),
            HexEditorInsertBytesMaximumTemplate = Pick("Allowed range: 1 to {0:N0} bytes", "允許範圍：1 至 {0:N0} bytes"),
            HexEditorInsertBytesActionLabel = Pick("Insert bytes", "插入 bytes"),
        };
    }
}

#pragma warning restore CS1591
