<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="NvtFwCombiner.Bootstrap.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NvtFwCombiner.Application\NvtFwCombiner.Application.csproj" />
    <ProjectReference Include="..\NvtFwCombiner.Infrastructure\NvtFwCombiner.Infrastructure.csproj" />
    <ProjectReference Include="..\NvtFwCombiner.Profiles\NvtFwCombiner.Profiles.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\profiles\built-in\nt51920-standard-merge\**\*">
      <Link>profiles\built-in\nt51920-standard-merge\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="..\..\profiles\built-in\nt51929-standard-merge\**\*">
      <Link>profiles\built-in\nt51929-standard-merge\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="..\..\profiles\built-in\nt51923-standard-merge\**\*">
      <Link>profiles\built-in\nt51923-standard-merge\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="..\..\profiles\built-in\nt51930-standard-merge\**\*">
      <Link>profiles\built-in\nt51930-standard-merge\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="..\..\profiles\built-in\nt51931-standard-merge\**\*">
      <Link>profiles\built-in\nt51931-standard-merge\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="..\..\profiles\built-in\nt51927-standard-merge\**\*">
      <Link>profiles\built-in\nt51927-standard-merge\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="..\..\profiles\built-in\nt51928-standard-merge\**\*">
      <Link>profiles\built-in\nt51928-standard-merge\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="..\..\profiles\built-in\nt51950-nt51951-standard-merge\**\*">
      <Link>profiles\built-in\nt51950-nt51951-standard-merge\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
