<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NvtFwCombiner.Application\NvtFwCombiner.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="SyntheticCompositionProfiles.cs" />
  </ItemGroup>
</Project>
