<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NvtFwCombiner.Domain\NvtFwCombiner.Domain.csproj" />
    <ProjectReference Include="..\NvtFwCombiner.Contracts\NvtFwCombiner.Contracts.csproj" />
    <ProjectReference Include="..\NvtFwCombiner.Application\NvtFwCombiner.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NvtFwCombiner.Infrastructure.Tests" />
  </ItemGroup>
</Project>
